# SQL Data Analysis Workshop

 This workshop is designed to help you build practical SQL skills by analyzing real-world business data. 
     
The tasks are divided into 4 levels to gradually progress from basic data retrieval to advanced analysis. Each level focuses on specific SQL concepts and challenges, allowing you to practice query writing, data filtering, aggregations, joins, and subqueries.
- Level 1: Basic SQL queries (SELECT, WHERE, ORDER BY, COUNT).
- Level 2: Aggregations (SUM, AVG, GROUP BY) and basic joins.
- Level 3: Complex joins, subqueries, and multi-table analysis.
- Level 4: Advanced analytical tasks focused on complex queries, subqueries, and aggregations..

This structured approach ensures you build confidence and expertise in SQL, preparing you for real-world data analysis challenges. ðŸš€

---
## Setup the work environment

#### 1. Library's import

In [140]:
import pandas as pd
import mysql.connector
import sqlite3

#### 2. Connecting to the Database

In [141]:
db_connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database=" bike_store"
)
cursor = db_connection.cursor()
print("Connection established successfully.")

Connection established successfully.

#### 3. Setup for SQL Magic

In [3]:
%load_ext sql

In [4]:
%sql mysql+pymysql://root:@localhost/bike_store

Connecting to 'mysql+pymysql://root:***@localhost/bike_store'


---
## Level 1: Beginner â€“ Basic Queries (using SQL Magic)

### Task 1: Retrieve all rows and columns from the customers table.

In [5]:
%sql SELECT * FROM customers

Running query in 'mysql+pymysql://root:***@localhost/bike_store'

1445 rows affected.

+-------------+------------+-----------+----------------+----------------------------+-------------------------+-----------------+-------+----------+
| customer_id | first_name | last_name |     phone      |           email            |          street         |       city      | state | zip_code |
+-------------+------------+-----------+----------------+----------------------------+-------------------------+-----------------+-------+----------+
|      1      |   Debra    |   Burks   |      None      |   debra.burks@yahoo.com    |    9273 Thorne Ave.     |   Orchard Park  |   NY  |  14127   |
|      2      |   Kasha    |    Todd   |      None      |    kasha.todd@yahoo.com    |     910 Vine Street     |     Campbell    |   CA  |  95008   |
|      3      |   Tameka   |   Fisher  |      None      |   tameka.fisher@aol.com    |  769C Honey Creek St.   |  Redondo Beach  |   CA  |  90278   |
|      4      |   Daryl    |   Spence  |      None      |    daryl.spence@aol.com    |     988 Pearl Lane      |    Uniondale    |   NY  |  11553   |
|      5      | Charolette |    Rice   | (916) 381-6003 |  charolette.rice@msn.com   |      107 River Dr.      |    Sacramento   |   CA  |  95820   |
|      6      |  Lyndsey   |    Bean   |      None      |  lyndsey.bean@hotmail.com  |      769 West Road      |     Fairport    |   NY  |  14450   |
|      7      |  Latasha   |    Hays   | (716) 986-3359 |  latasha.hays@hotmail.com  | 7014 Manor Station Rd.  |     Buffalo     |   NY  |  14215   |
|      8      | Jacquline  |   Duncan  |      None      | jacquline.duncan@yahoo.com |      15 Brown St.       | Jackson Heights |   NY  |  11372   |
|      9      |  Genoveva  |  Baldwin  |      None      |  genoveva.baldwin@msn.com  |    8550 Spruce Drive    | Port Washington |   NY  |  11050   |
|      10     |  Pamelia   |   Newman  |      None      |  pamelia.newman@gmail.com  |    476 Chestnut Ave.    |      Monroe     |   NY  |  10950   |
+-------------+------------+-----------+----------------+----------------------------+-------------------------+-----------------+-------+----------+
Truncated to displaylimit of 10.

### Task 2: Retrieve customers who live in the city "New York".

In [6]:
%sql SELECT * FROM customers where city = "New York"

Running query in 'mysql+pymysql://root:***@localhost/bike_store'

7 rows affected.

+-------------+------------+-----------+----------------+----------------------------+---------------------------+----------+-------+----------+
| customer_id | first_name | last_name |     phone      |           email            |           street          |   city   | state | zip_code |
+-------------+------------+-----------+----------------+----------------------------+---------------------------+----------+-------+----------+
|      16     |   Emmitt   |  Sanchez  | (212) 945-8823 | emmitt.sanchez@hotmail.com |   461 Squaw Creek Road    | New York |   NY  |  10002   |
|     178     |  Genoveva  |   Tyler   | (212) 152-6381 |  genoveva.tyler@gmail.com  |    8121 Windfall Ave.     | New York |   NY  |  10002   |
|     327     |   Sharie   |  Alvarez  | (212) 211-7621 |   sharie.alvarez@msn.com   | 987 West Leatherwood Dr.  | New York |   NY  |  10002   |
|     411     |  Octavia   |    Case   | (212) 171-1335 |    octavia.case@aol.com    |      40 Charles Road      | New York |   NY  |  10002   |
|     854     |   Phylis   |   Adkins  | (212) 325-9145 |   phylis.adkins@msn.com    |      7781 James Ave.      | New York |   NY  |  10002   |
|     927     | Guillermo  |    Hart   | (212) 652-7198 | guillermo.hart@hotmail.com |  81 Indian Summer Drive   | New York |   NY  |  10002   |
|     1016    |   Shenna   |   Benton  | (212) 578-2912 |   shenna.benton@msn.com    |   57 Shadow Brook Road    | New York |   NY  |  10002   |
+-------------+------------+-----------+----------------+----------------------------+---------------------------+----------+-------+----------+

### Task 3: Retrieve all products sorted by their price in descending order.

In [7]:
%sql SELECT * FROM products order by list_price DESC

Running query in 'mysql+pymysql://root:***@localhost/bike_store'

321 rows affected.

+------------+----------------------------------------+----------+-------------+------------+------------+
| product_id |              product_name              | brand_id | category_id | model_year | list_price |
+------------+----------------------------------------+----------+-------------+------------+------------+
|    155     |     Trek Domane SLR 9 Disc - 2018      |    9     |      7      |    2018    |  11999.99  |
|    149     |     Trek Domane SLR 8 Disc - 2018      |    9     |      7      |    2018    |  7499.99   |
|     51     |    Trek Silque SLR 8 Women's - 2017    |    9     |      7      |    2017    |  6499.99   |
|    169     |        Trek Emonda SLR 8 - 2018        |    9     |      7      |    2018    |  6499.99   |
|    157     | Trek Domane SL Frameset Women's - 2018 |    9     |      7      |    2018    |  6499.99   |
|    156     |     Trek Domane SL Frameset - 2018     |    9     |      7      |    2018    |  6499.99   |
|     50     |    Trek Silque SLR 7 Women's - 2017    |    9     |      7      |    2017    |  5999.99   |
|    177     |     Trek Domane SLR 6 Disc - 2018      |    9     |      7      |    2018    |  5499.99   |
|    154     | Trek Domane SLR 6 Disc Women's - 2018  |    9     |      7      |    2018    |  5499.99   |
|    148     |      Trek Domane SL 8 Disc - 2018      |    9     |      7      |    2018    |  5499.99   |
+------------+----------------------------------------+----------+-------------+------------+------------+
Truncated to displaylimit of 10.

### Task 4: Find Orders by Status

#### Task 4.1: Retrieve all orders with status "Completed".

In [8]:
%%sql SELECT o.order_id , o.order_status, os.status_description FROM orders o 
    Join order_statuses os on o.order_status = os.status_id

Running query in 'mysql+pymysql://root:***@localhost/bike_store'

1615 rows affected.

+----------+--------------+--------------------+
| order_id | order_status | status_description |
+----------+--------------+--------------------+
|    1     |      4       |     Completed      |
|    2     |      4       |     Completed      |
|    3     |      4       |     Completed      |
|    4     |      4       |     Completed      |
|    5     |      4       |     Completed      |
|    6     |      4       |     Completed      |
|    7     |      4       |     Completed      |
|    8     |      4       |     Completed      |
|    9     |      4       |     Completed      |
|    10    |      4       |     Completed      |
+----------+--------------+--------------------+
Truncated to displaylimit of 10.

#### Task 4.1: Retrieve count of orders with status "Rejected".

In [9]:
%%sql SELECT COUNT(*) as Rejected_orders FROM orders o 
    Join order_statuses os on o.order_status = os.status_id
    WHERE os.status_description = 'Rejected'

Running query in 'mysql+pymysql://root:***@localhost/bike_store'

1 rows affected.

+-----------------+
| Rejected_orders |
+-----------------+
|        45       |
+-----------------+

### Task 5: Count how many customers exist in the customers table.

In [10]:
%sql SELECT COUNT(*) as No_of_customers FROM customers

Running query in 'mysql+pymysql://root:***@localhost/bike_store'

1 rows affected.

+-----------------+
| No_of_customers |
+-----------------+
|       1445      |
+-----------------+

---
## Level 2: Intermediate â€“ Aggregations and Basic Joins
##### (Task 1,2,3 using Pandas read_sql and Task 4,5 using execute and fetchall() in mysql.connector)

### Task 1: Calculate the total revenue (sum of list_price * quantity) from the order_items table.

In [11]:
orderitems = pd.read_sql("SELECT * FROM order_items;", db_connection)

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\1224598945.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orderitems = pd.read_sql("SELECT * FROM order_items;", db_connection)

In [17]:
# pandas' method
orderitems['total_revenue'] = (orderitems['list_price'] * orderitems['quantity'] * (1 - orderitems["discount"])).sum()
print(orderitems['total_revenue'])

0       7.689117e+06
1       7.689117e+06
2       7.689117e+06
3       7.689117e+06
4       7.689117e+06
            ...
4717    7.689117e+06
4718    7.689117e+06
4719    7.689117e+06
4720    7.689117e+06
4721    7.689117e+06
Name: total_revenue, Length: 4722, dtype: float64

In [14]:
# sql
result = pd.read_sql("SELECT sum(list_price * quantity * (1-discount)) as Total_Revenue FROM order_items;", db_connection)
result

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\612365626.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql("SELECT sum(list_price * quantity * (1-discount)) as Total_Revenue FROM order_items;", db_connection)

   Total_Revenue
0   7.689117e+06

### Task 2: Calculate the average price of products in the products table.

In [15]:
products = pd.read_sql("SELECT * FROM products;", db_connection)

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\848119615.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql("SELECT * FROM products;", db_connection)

In [16]:
# pandas' method
products['average'] = products['list_price'].mean()
print(products['average'])

0      1520.591402
1      1520.591402
2      1520.591402
3      1520.591402
4      1520.591402
          ...
316    1520.591402
317    1520.591402
318    1520.591402
319    1520.591402
320    1520.591402
Name: average, Length: 321, dtype: float64

In [18]:
# sql
result = pd.read_sql("SELECT avg(list_price) as Average FROM products;", db_connection)
result

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\2240724601.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql("SELECT avg(list_price) as Average FROM products;", db_connection)

       Average
0  1520.591402

### Task 3: Retrieve the number of orders placed by each customer.

In [19]:
customers = pd.read_sql("SELECT * FROM customers;", db_connection)
orders = pd.read_sql("SELECT * FROM orders;", db_connection)

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\1766752683.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers = pd.read_sql("SELECT * FROM customers;", db_connection)
C:\Users\Client\AppData\Local\Temp\ipykernel_8160\1766752683.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders = pd.read_sql("SELECT * FROM orders;", db_connection)

In [20]:
# pandas' method
customerOrders = orders.groupby("customer_id")["order_id"].count()
join = pd.merge(customers, customerOrders, on="customer_id", how="left")
join.rename(columns={"order_id": "order_count"}, inplace=True)
print(join[["customer_id", "first_name", "last_name", "order_count"]])

      customer_id  first_name last_name  order_count
0               1       Debra     Burks            3
1               2       Kasha      Todd            3
2               3      Tameka    Fisher            3
3               4       Daryl    Spence            3
4               5  Charolette      Rice            3
...           ...         ...       ...          ...
1440         1441      Jamaal  Morrison            1
1441         1442      Cassie     Cline            1
1442         1443      Lezlie      Lamb            1
1443         1444      Ivette     Estes            1
1444         1445       Ester   Acevedo            1

[1445 rows x 4 columns]

In [24]:
# sql
result = pd.read_sql("""SELECT c.customer_id, CONCAT(c.first_name, " " ,c.last_name) As Full_name, COUNT(o.order_id) AS order_count
            FROM customers c
            LEFT JOIN orders o 
            ON c.customer_id = o.customer_id
            GROUP BY c.customer_id;""", db_connection)
result

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\695624683.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql("""SELECT c.customer_id, CONCAT(c.first_name, " " ,c.last_name) As Full_name, COUNT(o.order_id) AS order_count

      customer_id        Full_name  order_count
0               1      Debra Burks            3
1               2       Kasha Todd            3
2               3    Tameka Fisher            3
3               4     Daryl Spence            3
4               5  Charolette Rice            3
...           ...              ...          ...
1440         1441  Jamaal Morrison            1
1441         1442     Cassie Cline            1
1442         1443      Lezlie Lamb            1
1443         1444     Ivette Estes            1
1444         1445    Ester Acevedo            1

[1445 rows x 3 columns]

### Task 4: Join Orders with Customers

#### Task 4.1: Retrieve customer names along with their order IDs.

In [51]:
sql_query_1 = """SELECT c.first_name, c.last_name, o.order_id
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id;"""
cursor.execute(sql_query_1)
output1 = cursor.fetchall()

for row in output1:
    print(f"Customer: {row[0]} {row[1]}, Order_id: {row[2]}")

Customer: Debra Burks, Order_id: 599
Customer: Debra Burks, Order_id: 1555
Customer: Debra Burks, Order_id: 1613
Customer: Kasha Todd, Order_id: 692
Customer: Kasha Todd, Order_id: 1084
Customer: Kasha Todd, Order_id: 1509
Customer: Tameka Fisher, Order_id: 1468
Customer: Tameka Fisher, Order_id: 1496
Customer: Tameka Fisher, Order_id: 1612
Customer: Daryl Spence, Order_id: 700
Customer: Daryl Spence, Order_id: 1259
Customer: Daryl Spence, Order_id: 1556
Customer: Charolette Rice, Order_id: 264
Customer: Charolette Rice, Order_id: 571
Customer: Charolette Rice, Order_id: 1544
Customer: Lyndsey Bean, Order_id: 1059
Customer: Lyndsey Bean, Order_id: 1592
Customer: Lyndsey Bean, Order_id: 1611
Customer: Latasha Hays, Order_id: 104
Customer: Latasha Hays, Order_id: 1532
Customer: Latasha Hays, Order_id: 1604
Customer: Jacquline Duncan, Order_id: 512
Customer: Jacquline Duncan, Order_id: 1010
Customer: Jacquline Duncan, Order_id: 1523
Customer: Genoveva Baldwin, Order_id: 76
Customer: Genoveva Baldwin, Order_id: 1459
Customer: Genoveva Baldwin, Order_id: 1593
Customer: Pamelia Newman, Order_id: 825
Customer: Pamelia Newman, Order_id: 1541
Customer: Pamelia Newman, Order_id: 1609
Customer: Deshawn Mendoza, Order_id: 1074
Customer: Deshawn Mendoza, Order_id: 1387
Customer: Deshawn Mendoza, Order_id: 1588
Customer: Robby Sykes, Order_id: 108
Customer: Robby Sykes, Order_id: 715
Customer: Robby Sykes, Order_id: 1576
Customer: Lashawn Ortiz, Order_id: 239
Customer: Lashawn Ortiz, Order_id: 852
Customer: Lashawn Ortiz, Order_id: 1527
Customer: Garry Espinoza, Order_id: 357
Customer: Garry Espinoza, Order_id: 419
Customer: Garry Espinoza, Order_id: 1572
Customer: Linnie Branch, Order_id: 1401
Customer: Linnie Branch, Order_id: 1483
Customer: Linnie Branch, Order_id: 1610
Customer: Emmitt Sanchez, Order_id: 352
Customer: Emmitt Sanchez, Order_id: 1020
Customer: Emmitt Sanchez, Order_id: 1510
Customer: Caren Stephens, Order_id: 246
Customer: Caren Stephens, Order_id: 301
Customer: Caren Stephens, Order_id: 1549
Customer: Georgetta Hardin, Order_id: 606
Customer: Georgetta Hardin, Order_id: 1407
Customer: Georgetta Hardin, Order_id: 1534
Customer: Lizzette Stein, Order_id: 1211
Customer: Lizzette Stein, Order_id: 1234
Customer: Lizzette Stein, Order_id: 1535
Customer: Aleta Shepard, Order_id: 547
Customer: Aleta Shepard, Order_id: 735
Customer: Aleta Shepard, Order_id: 1528
Customer: Tobie Little, Order_id: 1177
Customer: Tobie Little, Order_id: 1409
Customer: Tobie Little, Order_id: 1596
Customer: Adelle Larsen, Order_id: 183
Customer: Adelle Larsen, Order_id: 1505
Customer: Kaylee English, Order_id: 1109
Customer: Kaylee English, Order_id: 1479
Customer: Corene Wall, Order_id: 185
Customer: Corene Wall, Order_id: 1157
Customer: Corene Wall, Order_id: 1573
Customer: Regenia Vaughan, Order_id: 1065
Customer: Regenia Vaughan, Order_id: 1511
Customer: Theo Reese, Order_id: 256
Customer: Theo Reese, Order_id: 1519
Customer: Santos Valencia, Order_id: 634
Customer: Santos Valencia, Order_id: 1480
Customer: Jeanice Frost, Order_id: 1306
Customer: Jeanice Frost, Order_id: 1533
Customer: Syreeta Hendricks, Order_id: 665
Customer: Syreeta Hendricks, Order_id: 1569
Customer: Jamaal Albert, Order_id: 349
Customer: Jamaal Albert, Order_id: 444
Customer: Jamaal Albert, Order_id: 1553
Customer: Williemae Holloway, Order_id: 162
Customer: Williemae Holloway, Order_id: 350
Customer: Williemae Holloway, Order_id: 1497
Customer: Araceli Golden, Order_id: 159
Customer: Araceli Golden, Order_id: 582
Customer: Araceli Golden, Order_id: 1513
Customer: Deloris Burke, Order_id: 575
Customer: Deloris Burke, Order_id: 1487
Customer: Deloris Burke, Order_id: 1607
Customer: Brittney Woodward, Order_id: 1190
Customer: Brittney Woodward, Order_id: 1536
Customer: Guillermina Noble, Order_id: 1476
Customer: Guillermina Noble, Order_id: 1484
Customer: Bernita Mcdaniel, Order_id: 303
Customer: Bernita Mcdaniel, Order_id: 1537
Customer: Melia Brady, Order_id: 1295
Customer: Melia Brady, Order_id: 1524
Customer: Zelma Browning, Order_id: 718
Customer: Zelma Browning, Order_id: 1525
Customer: Janetta Aguirre, Order_id: 1322
Customer: Janetta Aguirre, Order_id: 1550
Customer: Ronna Butler, Order_id: 598
Customer: Ronna Butler, Order_id: 1092
Customer: Ronna Butler, Order_id: 1589
Customer: Kathie Freeman, Order_id: 1161
Customer: Kathie Freeman, Order_id: 1492
Customer: Tangela Quinn, Order_id: 1076
Customer: Tangela Quinn, Order_id: 1559
Customer: Mozelle Carter, Order_id: 157
Customer: Mozelle Carter, Order_id: 935
Customer: Mozelle Carter, Order_id: 1601
Customer: Onita Johns, Order_id: 1253
Customer: Onita Johns, Order_id: 1583
Customer: Bennett Armstrong, Order_id: 826
Customer: Bennett Armstrong, Order_id: 1594
Customer: Monika Berg, Order_id: 132
Customer: Monika Berg, Order_id: 1089
Customer: Monika Berg, Order_id: 1564
Customer: Bridgette Guerra, Order_id: 897
Customer: Bridgette Guerra, Order_id: 1072
Customer: Bridgette Guerra, Order_id: 1516
Customer: Cesar Jackson, Order_id: 1200
Customer: Cesar Jackson, Order_id: 1577
Customer: Caroll Hays, Order_id: 739
Customer: Caroll Hays, Order_id: 1599
Customer: Cleotilde Booth, Order_id: 70
Customer: Cleotilde Booth, Order_id: 593
Customer: Cleotilde Booth, Order_id: 1529
Customer: Gertrud Rhodes, Order_id: 222
Customer: Gertrud Rhodes, Order_id: 1485
Customer: Tu Ramirez, Order_id: 1116
Customer: Tu Ramirez, Order_id: 1501
Customer: Saturnina Garner, Order_id: 389
Customer: Saturnina Garner, Order_id: 1521
Customer: Saturnina Garner, Order_id: 1608
Customer: Fran Yang, Order_id: 519
Customer: Fran Yang, Order_id: 1570
Customer: Diana Guerra, Order_id: 147
Customer: Diana Guerra, Order_id: 1602
Customer: Lolita Mosley, Order_id: 778
Customer: Lolita Mosley, Order_id: 1413
Customer: Lolita Mosley, Order_id: 1597
Customer: Pamala Henry, Order_id: 27
Customer: Pamala Henry, Order_id: 1560
Customer: Damien Dorsey, Order_id: 694
Customer: Damien Dorsey, Order_id: 1542
Customer: Latasha Stanley, Order_id: 286
Customer: Latasha Stanley, Order_id: 1526
Customer: Neil Mccall, Order_id: 9
Customer: Neil Mccall, Order_id: 1565
Customer: Elinore Aguilar, Order_id: 391
Customer: Elinore Aguilar, Order_id: 556
Customer: Elinore Aguilar, Order_id: 1515
Customer: Alica Hunter, Order_id: 543
Customer: Alica Hunter, Order_id: 1481
Customer: Tenisha Lyons, Order_id: 1390
Customer: Tenisha Lyons, Order_id: 1558
Customer: Bobbie Foster, Order_id: 549
Customer: Bobbie Foster, Order_id: 673
Customer: Bobbie Foster, Order_id: 1493
Customer: Kanesha Vega, Order_id: 240
Customer: Kanesha Vega, Order_id: 1561
Customer: Lorrie Becker, Order_id: 252
Customer: Lorrie Becker, Order_id: 885
Customer: Lorrie Becker, Order_id: 1520
Customer: Tommie Melton, Order_id: 424
Customer: Tommie Melton, Order_id: 1545
Customer: Jayne Kirkland, Order_id: 924
Customer: Jayne Kirkland, Order_id: 1325
Customer: Jayne Kirkland, Order_id: 1512
Customer: Katelin Kennedy, Order_id: 1130
Customer: Katelin Kennedy, Order_id: 1494
Customer: Tomasa Carson, Order_id: 1041
Customer: Tomasa Carson, Order_id: 1551
Customer: Takako Casey, Order_id: 1360
Customer: Takako Casey, Order_id: 1595
Customer: Petronila Norris, Order_id: 420
Customer: Petronila Norris, Order_id: 1566
Customer: Melanie Hayes, Order_id: 937
Customer: Melanie Hayes, Order_id: 1552
Customer: Georgeann Waller, Order_id: 464
Customer: Georgeann Waller, Order_id: 1603
Customer: Abby Gamble, Order_id: 1318
Customer: Abby Gamble, Order_id: 1506
Customer: Parker Prince, Order_id: 152
Customer: Parker Prince, Order_id: 1543
Customer: Keri Bridges, Order_id: 407
Customer: Keri Bridges, Order_id: 435
Customer: Keri Bridges, Order_id: 1563
Customer: Chi Goff, Order_id: 801
Customer: Chi Goff, Order_id: 1522
Customer: Ashanti Parks, Order_id: 707
Customer: Ashanti Parks, Order_id: 1538
Customer: Sarai Mckee, Order_id: 34
Customer: Sarai Mckee, Order_id: 1571
Customer: Zina Bonner, Order_id: 679
Customer: Zina Bonner, Order_id: 1498
Customer: Lizzie Joyner, Order_id: 961
Customer: Lizzie Joyner, Order_id: 1491
Customer: Tiesha Daniel, Order_id: 327
Customer: Tiesha Daniel, Order_id: 1502
Customer: Armand Whitehead, Order_id: 129
Customer: Armand Whitehead, Order_id: 1486
Customer: Teofila Fischer, Order_id: 1283
Customer: Teofila Fischer, Order_id: 1507
Customer: Lissa Vargas, Order_id: 128
Customer: Lissa Vargas, Order_id: 1495
Customer: Yan Mcgowan, Order_id: 747
Customer: Yan Mcgowan, Order_id: 1514
Customer: Titus Bullock, Order_id: 418
Customer: Titus Bullock, Order_id: 1562
Customer: Arvilla Osborn, Order_id: 1229
Customer: Arvilla Osborn, Order_id: 1567
Customer: Marjorie Logan, Order_id: 561
Customer: Marjorie Logan, Order_id: 1600
Customer: Marvin Mullins, Order_id: 12
Customer: Marvin Mullins, Order_id: 1546
Customer: Tena Cruz, Order_id: 1369
Customer: Tena Cruz, Order_id: 1508
Customer: Corrina Sawyer, Order_id: 934
Customer: Corrina Sawyer, Order_id: 1578
Customer: Sharyn Hopkins, Order_id: 6
Customer: Sharyn Hopkins, Order_id: 1482
Customer: Letitia Franco, Order_id: 804
Customer: Floretta Higgins, Order_id: 604
Customer: Louanne Martin, Order_id: 867
Customer: Louanne Martin, Order_id: 1517
Customer: Violet Valenzuela, Order_id: 190
Customer: Carie Kidd, Order_id: 169
Customer: Kellie Franco, Order_id: 1405
Customer: Nichelle Howell, Order_id: 448
Customer: Marisol Goodman, Order_id: 588
Customer: Sylvie Wilkerson, Order_id: 401
Customer: Katharina Bates, Order_id: 554
Customer: Katharina Bates, Order_id: 1579
Customer: Marget Hodge, Order_id: 207
Customer: Raul Melendez, Order_id: 1066
Customer: Cecil Hopper, Order_id: 258
Customer: Shae Hickman, Order_id: 1297
Customer: Monica Sears, Order_id: 1411
Customer: Monica Sears, Order_id: 1584
Customer: Ollie Zimmerman, Order_id: 1252
Customer: Ollie Zimmerman, Order_id: 1530
Customer: Shila White, Order_id: 516
Customer: Yuk Vega, Order_id: 1475
Customer: Eliana Silva, Order_id: 1264
Customer: Thalia Horne, Order_id: 1472
Customer: Rey Lindsay, Order_id: 1370
Customer: Merlene Vinson, Order_id: 531
Customer: Merlene Vinson, Order_id: 1047
Customer: Merlene Vinson, Order_id: 1539
Customer: Dacia William, Order_id: 158
Customer: Dacia William, Order_id: 173
Customer: Le Wood, Order_id: 617
Customer: Thalia Dillard, Order_id: 741
Customer: Thalia Dillard, Order_id: 1606
Customer: Luz House, Order_id: 907
Customer: Luz House, Order_id: 1499
Customer: Lucy Woods, Order_id: 177
Customer: Lucy Woods, Order_id: 1557
Customer: Shena Carter, Order_id: 1364
Customer: Robena Hill, Order_id: 1280
Customer: Robena Hill, Order_id: 1605
Customer: Jeni Booker, Order_id: 738
Customer: Jeni Booker, Order_id: 1574
Customer: Herlinda Stone, Order_id: 1021
Customer: Lavina Dejesus, Order_id: 1425
Customer: Erlinda Nielsen, Order_id: 197
Customer: Terrance Lynn, Order_id: 1284
Customer: Walton Dejesus, Order_id: 938
Customer: Wes Stanton, Order_id: 626
Customer: Tanesha Hampton, Order_id: 618
Customer: Boyd Irwin, Order_id: 372
Customer: Delbert Wilkins, Order_id: 287
Customer: Brianna Moss, Order_id: 184
Customer: Dorthey Jackson, Order_id: 770
Customer: Dorthey Jackson, Order_id: 1614
Customer: Sarita Parks, Order_id: 1346
Customer: Sarita Parks, Order_id: 1615
Customer: Shonta Mercer, Order_id: 743
Customer: Jone Bernard, Order_id: 944
Customer: Jone Bernard, Order_id: 1590
Customer: Wanita Davenport, Order_id: 1461
Customer: Cleopatra Tate, Order_id: 1055
Customer: Ramiro Byers, Order_id: 766
Customer: Nicholas Vazquez, Order_id: 950
Customer: Janae Doyle, Order_id: 1121
Customer: Hans Price, Order_id: 395
Customer: Miquel Neal, Order_id: 249
Customer: Stefany Potter, Order_id: 1399
Customer: Bernetta Marquez, Order_id: 732
Customer: Julee Woodard, Order_id: 500
Customer: Meredith Bryan, Order_id: 439
Customer: Weldon Michael, Order_id: 250
Customer: Joesph Delacruz, Order_id: 60
Customer: Joesph Delacruz, Order_id: 1500
Customer: Katherina Odom, Order_id: 1467
Customer: Laraine Robbins, Order_id: 429
Customer: Laraine Robbins, Order_id: 810
Customer: Jenise Preston, Order_id: 796
Customer: Lory Page, Order_id: 513
Customer: Charlyn Cantrell, Order_id: 308
Customer: Carola Rodriquez, Order_id: 224
Customer: Carola Rodriquez, Order_id: 1585
Customer: Alane Kennedy, Order_id: 291
Customer: Regina Burns, Order_id: 282
Customer: Omer Estrada, Order_id: 579
Customer: Crystle Gilliam, Order_id: 1030
Customer: Kam Wilder, Order_id: 858
Customer: Margert Stevens, Order_id: 632
Customer: Tomika Larson, Order_id: 37
Customer: Jeromy Burch, Order_id: 1275
Customer: Jeromy Burch, Order_id: 1591
Customer: Lena Mills, Order_id: 744
Customer: Loreta Johnston, Order_id: 945
Customer: Nettie Mcdaniel, Order_id: 1017
Customer: Karla Kirk, Order_id: 432
Customer: Karla Kirk, Order_id: 1547
Customer: Regine Gonzales, Order_id: 142
Customer: Regine Gonzales, Order_id: 1548
Customer: Miriam Baker, Order_id: 890
Customer: Jeanie Kirkland, Order_id: 987
Customer: Jeanie Kirkland, Order_id: 1554
Customer: Marquerite Dawson, Order_id: 712
Customer: Babara Ochoa, Order_id: 1013
Customer: Nova Hess, Order_id: 4
Customer: Nova Hess, Order_id: 1518
Customer: Carley Reynolds, Order_id: 392
Customer: Carley Reynolds, Order_id: 1586
Customer: Carissa Foreman, Order_id: 854
Customer: Genoveva Tyler, Order_id: 572
Customer: Deane Sears, Order_id: 903
Customer: Karey Steele, Order_id: 1477
Customer: Olevia Pitts, Order_id: 283
Customer: Olevia Pitts, Order_id: 1488
Customer: Jenniffer Bullock, Order_id: 1060
Customer: Jeniffer Ratliff, Order_id: 187
Customer: Klara Stanley, Order_id: 736
Customer: Morton Lee, Order_id: 1045
Customer: Ken Charles, Order_id: 1191
Customer: Hedwig Paul, Order_id: 362
Customer: Hedwig Paul, Order_id: 1540
Customer: Sharla Flynn, Order_id: 909
Customer: Sharla Flynn, Order_id: 1581
Customer: Damian Dawson, Order_id: 1054
Customer: Toya Pratt, Order_id: 651
Customer: Graciela Barber, Order_id: 492
Customer: Graciela Barber, Order_id: 1580
Customer: Bong Hebert, Order_id: 1194
Customer: Bong Hebert, Order_id: 1568
Customer: Ayanna Rhodes, Order_id: 496
Customer: Dorine Roberson, Order_id: 1049
Customer: Dorine Roberson, Order_id: 1489
Customer: Addie Hahn, Order_id: 1428
Customer: Edythe Valencia, Order_id: 882
Customer: Andy O'neill, Order_id: 458
Customer: Luis Tyler, Order_id: 1063
Customer: Clelia Workman, Order_id: 382
Customer: Ashely Holmes, Order_id: 719
Customer: Candis Harding, Order_id: 1201
Customer: Marni Bolton, Order_id: 290
Customer: Minerva Decker, Order_id: 1333
Customer: Alpha King, Order_id: 97
Customer: Harris Pittman, Order_id: 160
Customer: Stephaine Riddle, Order_id: 236
Customer: Michel Blankenship, Order_id: 713
Customer: Denis Logan, Order_id: 62
Customer: Denis Logan, Order_id: 1503
Customer: Jutta Everett, Order_id: 1051
Customer: Priscilla Wilkins, Order_id: 1235
Customer: Gilma Dejesus, Order_id: 309
Customer: Buford Bridges, Order_id: 555
Customer: Elenore Hensley, Order_id: 1212
Customer: Ross Pugh, Order_id: 879
Customer: Judith Finley, Order_id: 915
Customer: Wai Soto, Order_id: 1183
Customer: Carline Collier, Order_id: 1321
Customer: Carline Collier, Order_id: 1490
Customer: Casey Gill, Order_id: 95
Customer: Darcie Morgan, Order_id: 998
Customer: Lucio Sherman, Order_id: 1086
Customer: Clementine Mooney, Order_id: 819
Customer: Anya Contreras, Order_id: 1206
Customer: Scarlet Yates, Order_id: 245
Customer: Moses Pope, Order_id: 878
Customer: Moses Pope, Order_id: 1575
Customer: Barbera Riggs, Order_id: 1067
Customer: Kiana Rivera, Order_id: 1226
Customer: Danielle Bond, Order_id: 1277
Customer: Whitney Estes, Order_id: 1448
Customer: Molly Langley, Order_id: 1195
Customer: Chelsey Hardin, Order_id: 304
Customer: Jenee Rasmussen, Order_id: 1296
Customer: Jenee Rasmussen, Order_id: 1587
Customer: Freddie Mathis, Order_id: 750
Customer: Mariana Strong, Order_id: 926
Customer: Mariana Strong, Order_id: 1531
Customer: Winfred Harris, Order_id: 806
Customer: Jeromy Elliott, Order_id: 509
Customer: Verona O'neill, Order_id: 33
Customer: Elvera Peck, Order_id: 171
Customer: Elvera Peck, Order_id: 1504
Customer: Cindi Larson, Order_id: 973
Customer: Felice Guzman, Order_id: 1050
Customer: Felice Guzman, Order_id: 1598
Customer: Le Deleon, Order_id: 421
Customer: Le Deleon, Order_id: 1582
Customer: Manie Sanchez, Order_id: 475
Customer: Rutha Howell, Order_id: 918
Customer: Natosha Rowland, Order_id: 1236
Customer: Jessika Bray, Order_id: 1320
Customer: Delila Hamilton, Order_id: 680
Customer: Dionne Norris, Order_id: 828
Customer: Muriel Juarez, Order_id: 1347
Customer: Cecelia Gill, Order_id: 969
Customer: Magda Eaton, Order_id: 786
Customer: Ivonne Yang, Order_id: 678
Customer: Kasie Rodriquez, Order_id: 161
Customer: Eleni Gordon, Order_id: 28
Customer: Maurice Norton, Order_id: 1358
Customer: Cristobal Hutchinson, Order_id: 1138
Customer: Flossie Holder, Order_id: 749
Customer: Erma Salinas, Order_id: 1332
Customer: Earl Stanley, Order_id: 1305
Customer: Maribel William, Order_id: 14
Customer: Johnathan Velazquez, Order_id: 1
Customer: Rodrick Shelton, Order_id: 499
Customer: Ferne Kline, Order_id: 411
Customer: Rubin Decker, Order_id: 1285
Customer: Dortha Jarvis, Order_id: 1438
Customer: Mariela Huffman, Order_id: 74
Customer: Mellisa Farley, Order_id: 936
Customer: Myung Hooper, Order_id: 1005
Customer: Angelina Lloyd, Order_id: 216
Customer: Trinity Riddle, Order_id: 1104
Customer: Barton Crosby, Order_id: 1197
Customer: Claudio Wise, Order_id: 972
Customer: Katheleen Marks, Order_id: 101
Customer: Deja Chaney, Order_id: 430
Customer: Queenie Vance, Order_id: 1323
Customer: Josh Shaw, Order_id: 329
Customer: Pinkie Kirkland, Order_id: 1124
Customer: Lavette Wright, Order_id: 86
Customer: Mark Garrett, Order_id: 61
Customer: Myesha Burgess, Order_id: 947
Customer: Justina Long, Order_id: 1287
Customer: Brenda Tate, Order_id: 201
Customer: Rayna Perry, Order_id: 299
Customer: Randolph Chase, Order_id: 267
Customer: Jaimee Day, Order_id: 647
Customer: Susann Bass, Order_id: 759
Customer: Leola Gould, Order_id: 1292
Customer: Virgil Frost, Order_id: 1166
Customer: Mireille Puckett, Order_id: 1452
Customer: Keturah Massey, Order_id: 146
Customer: Charmain Webster, Order_id: 1251
Customer: Barry Buckner, Order_id: 1018
Customer: Boyce Burks, Order_id: 675
Customer: Monty Frost, Order_id: 1175
Customer: Tiny French, Order_id: 1414
Customer: Clementina Sargent, Order_id: 822
Customer: Danny Kim, Order_id: 710
Customer: Sophia Mcmillan, Order_id: 1450
Customer: Christia Carson, Order_id: 668
Customer: Jennie Middleton, Order_id: 566
Customer: Jame Riggs, Order_id: 312
Customer: Rayford Simon, Order_id: 1417
Customer: Annett Garrett, Order_id: 817
Customer: Hayden Cross, Order_id: 1473
Customer: Rolanda Larsen, Order_id: 1242
Customer: Jayme Zamora, Order_id: 478
Customer: Hope Cotton, Order_id: 1085
Customer: Vikki Erickson, Order_id: 105
Customer: Fransisca Nicholson, Order_id: 225
Customer: Mazie Fernandez, Order_id: 1431
Customer: Anderson Martin, Order_id: 607
Customer: Gilberto Parsons, Order_id: 1362
Customer: Charise Burt, Order_id: 1312
Customer: Cameron Carroll, Order_id: 1375
Customer: Melani Jarvis, Order_id: 542
Customer: Javier Nichols, Order_id: 438
Customer: Justina Jenkins, Order_id: 808
Customer: Hortencia Graham, Order_id: 131
Customer: Christia Wilkins, Order_id: 84
Customer: Eliz Whitney, Order_id: 1199
Customer: Justin Newton, Order_id: 285
Customer: Aron Wiggins, Order_id: 1282
Customer: Chere Hardin, Order_id: 544
Customer: Merideth Preston, Order_id: 1302
Customer: Jeniffer Slater, Order_id: 1388
Customer: Laureen Paul, Order_id: 7
Customer: Berna Moore, Order_id: 1056
Customer: Shiela Calderon, Order_id: 1093
Customer: Sharie Alvarez, Order_id: 120
Customer: Bettie Glover, Order_id: 980
Customer: Marilyn Frank, Order_id: 847
Customer: Sheba Knapp, Order_id: 1449
Customer: Aleta Mack, Order_id: 383
Customer: Reena Higgins, Order_id: 150
Customer: Ami Mcmahon, Order_id: 1244
Customer: Somer Jordan, Order_id: 1117

#### Task 4.2: Retrieve Customer Names with Order IDs and Total Orders

In [26]:
sql_query_2 = """SELECT c.first_name, c.last_name, o.order_id, COUNT(o2.order_id) AS total_orders
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN orders o2 ON c.customer_id = o2.customer_id
GROUP BY c.customer_id, o.order_id, c.first_name, c.last_name
ORDER BY c.customer_id, o.order_id;"""
cursor.execute(sql_query_2)
output2 = cursor.fetchall()

for row in output2:
    print(f"Customer: {row[0]} {row[1]}, Order_id: {row[2]} , Total_orders: {row[3]}")

Customer: Debra Burks, Order_id: 599 , Total_orders: 3
Customer: Debra Burks, Order_id: 1555 , Total_orders: 3
Customer: Debra Burks, Order_id: 1613 , Total_orders: 3
Customer: Kasha Todd, Order_id: 692 , Total_orders: 3
Customer: Kasha Todd, Order_id: 1084 , Total_orders: 3
Customer: Kasha Todd, Order_id: 1509 , Total_orders: 3
Customer: Tameka Fisher, Order_id: 1468 , Total_orders: 3
Customer: Tameka Fisher, Order_id: 1496 , Total_orders: 3
Customer: Tameka Fisher, Order_id: 1612 , Total_orders: 3
Customer: Daryl Spence, Order_id: 700 , Total_orders: 3
Customer: Daryl Spence, Order_id: 1259 , Total_orders: 3
Customer: Daryl Spence, Order_id: 1556 , Total_orders: 3
Customer: Charolette Rice, Order_id: 264 , Total_orders: 3
Customer: Charolette Rice, Order_id: 571 , Total_orders: 3
Customer: Charolette Rice, Order_id: 1544 , Total_orders: 3
Customer: Lyndsey Bean, Order_id: 1059 , Total_orders: 3
Customer: Lyndsey Bean, Order_id: 1592 , Total_orders: 3
Customer: Lyndsey Bean, Order_id: 1611 , Total_orders: 3
Customer: Latasha Hays, Order_id: 104 , Total_orders: 3
Customer: Latasha Hays, Order_id: 1532 , Total_orders: 3
Customer: Latasha Hays, Order_id: 1604 , Total_orders: 3
Customer: Jacquline Duncan, Order_id: 512 , Total_orders: 3
Customer: Jacquline Duncan, Order_id: 1010 , Total_orders: 3
Customer: Jacquline Duncan, Order_id: 1523 , Total_orders: 3
Customer: Genoveva Baldwin, Order_id: 76 , Total_orders: 3
Customer: Genoveva Baldwin, Order_id: 1459 , Total_orders: 3
Customer: Genoveva Baldwin, Order_id: 1593 , Total_orders: 3
Customer: Pamelia Newman, Order_id: 825 , Total_orders: 3
Customer: Pamelia Newman, Order_id: 1541 , Total_orders: 3
Customer: Pamelia Newman, Order_id: 1609 , Total_orders: 3
Customer: Deshawn Mendoza, Order_id: 1074 , Total_orders: 3
Customer: Deshawn Mendoza, Order_id: 1387 , Total_orders: 3
Customer: Deshawn Mendoza, Order_id: 1588 , Total_orders: 3
Customer: Robby Sykes, Order_id: 108 , Total_orders: 3
Customer: Robby Sykes, Order_id: 715 , Total_orders: 3
Customer: Robby Sykes, Order_id: 1576 , Total_orders: 3
Customer: Lashawn Ortiz, Order_id: 239 , Total_orders: 3
Customer: Lashawn Ortiz, Order_id: 852 , Total_orders: 3
Customer: Lashawn Ortiz, Order_id: 1527 , Total_orders: 3
Customer: Garry Espinoza, Order_id: 357 , Total_orders: 3
Customer: Garry Espinoza, Order_id: 419 , Total_orders: 3
Customer: Garry Espinoza, Order_id: 1572 , Total_orders: 3
Customer: Linnie Branch, Order_id: 1401 , Total_orders: 3
Customer: Linnie Branch, Order_id: 1483 , Total_orders: 3
Customer: Linnie Branch, Order_id: 1610 , Total_orders: 3
Customer: Emmitt Sanchez, Order_id: 352 , Total_orders: 3
Customer: Emmitt Sanchez, Order_id: 1020 , Total_orders: 3
Customer: Emmitt Sanchez, Order_id: 1510 , Total_orders: 3
Customer: Caren Stephens, Order_id: 246 , Total_orders: 3
Customer: Caren Stephens, Order_id: 301 , Total_orders: 3
Customer: Caren Stephens, Order_id: 1549 , Total_orders: 3
Customer: Georgetta Hardin, Order_id: 606 , Total_orders: 3
Customer: Georgetta Hardin, Order_id: 1407 , Total_orders: 3
Customer: Georgetta Hardin, Order_id: 1534 , Total_orders: 3
Customer: Lizzette Stein, Order_id: 1211 , Total_orders: 3
Customer: Lizzette Stein, Order_id: 1234 , Total_orders: 3
Customer: Lizzette Stein, Order_id: 1535 , Total_orders: 3
Customer: Aleta Shepard, Order_id: 547 , Total_orders: 3
Customer: Aleta Shepard, Order_id: 735 , Total_orders: 3
Customer: Aleta Shepard, Order_id: 1528 , Total_orders: 3
Customer: Tobie Little, Order_id: 1177 , Total_orders: 3
Customer: Tobie Little, Order_id: 1409 , Total_orders: 3
Customer: Tobie Little, Order_id: 1596 , Total_orders: 3
Customer: Adelle Larsen, Order_id: 183 , Total_orders: 2
Customer: Adelle Larsen, Order_id: 1505 , Total_orders: 2
Customer: Kaylee English, Order_id: 1109 , Total_orders: 2
Customer: Kaylee English, Order_id: 1479 , Total_orders: 2
Customer: Corene Wall, Order_id: 185 , Total_orders: 3
Customer: Corene Wall, Order_id: 1157 , Total_orders: 3
Customer: Corene Wall, Order_id: 1573 , Total_orders: 3
Customer: Regenia Vaughan, Order_id: 1065 , Total_orders: 2
Customer: Regenia Vaughan, Order_id: 1511 , Total_orders: 2
Customer: Theo Reese, Order_id: 256 , Total_orders: 2
Customer: Theo Reese, Order_id: 1519 , Total_orders: 2
Customer: Santos Valencia, Order_id: 634 , Total_orders: 2
Customer: Santos Valencia, Order_id: 1480 , Total_orders: 2
Customer: Jeanice Frost, Order_id: 1306 , Total_orders: 2
Customer: Jeanice Frost, Order_id: 1533 , Total_orders: 2
Customer: Syreeta Hendricks, Order_id: 665 , Total_orders: 2
Customer: Syreeta Hendricks, Order_id: 1569 , Total_orders: 2
Customer: Jamaal Albert, Order_id: 349 , Total_orders: 3
Customer: Jamaal Albert, Order_id: 444 , Total_orders: 3
Customer: Jamaal Albert, Order_id: 1553 , Total_orders: 3
Customer: Williemae Holloway, Order_id: 162 , Total_orders: 3
Customer: Williemae Holloway, Order_id: 350 , Total_orders: 3
Customer: Williemae Holloway, Order_id: 1497 , Total_orders: 3
Customer: Araceli Golden, Order_id: 159 , Total_orders: 3
Customer: Araceli Golden, Order_id: 582 , Total_orders: 3
Customer: Araceli Golden, Order_id: 1513 , Total_orders: 3
Customer: Deloris Burke, Order_id: 575 , Total_orders: 3
Customer: Deloris Burke, Order_id: 1487 , Total_orders: 3
Customer: Deloris Burke, Order_id: 1607 , Total_orders: 3
Customer: Brittney Woodward, Order_id: 1190 , Total_orders: 2
Customer: Brittney Woodward, Order_id: 1536 , Total_orders: 2
Customer: Guillermina Noble, Order_id: 1476 , Total_orders: 2
Customer: Guillermina Noble, Order_id: 1484 , Total_orders: 2
Customer: Bernita Mcdaniel, Order_id: 303 , Total_orders: 2
Customer: Bernita Mcdaniel, Order_id: 1537 , Total_orders: 2
Customer: Melia Brady, Order_id: 1295 , Total_orders: 2
Customer: Melia Brady, Order_id: 1524 , Total_orders: 2
Customer: Zelma Browning, Order_id: 718 , Total_orders: 2
Customer: Zelma Browning, Order_id: 1525 , Total_orders: 2
Customer: Janetta Aguirre, Order_id: 1322 , Total_orders: 2
Customer: Janetta Aguirre, Order_id: 1550 , Total_orders: 2
Customer: Ronna Butler, Order_id: 598 , Total_orders: 3
Customer: Ronna Butler, Order_id: 1092 , Total_orders: 3
Customer: Ronna Butler, Order_id: 1589 , Total_orders: 3
Customer: Kathie Freeman, Order_id: 1161 , Total_orders: 2
Customer: Kathie Freeman, Order_id: 1492 , Total_orders: 2
Customer: Tangela Quinn, Order_id: 1076 , Total_orders: 2
Customer: Tangela Quinn, Order_id: 1559 , Total_orders: 2
Customer: Mozelle Carter, Order_id: 157 , Total_orders: 3
Customer: Mozelle Carter, Order_id: 935 , Total_orders: 3
Customer: Mozelle Carter, Order_id: 1601 , Total_orders: 3
Customer: Onita Johns, Order_id: 1253 , Total_orders: 2
Customer: Onita Johns, Order_id: 1583 , Total_orders: 2
Customer: Bennett Armstrong, Order_id: 826 , Total_orders: 2
Customer: Bennett Armstrong, Order_id: 1594 , Total_orders: 2
Customer: Monika Berg, Order_id: 132 , Total_orders: 3
Customer: Monika Berg, Order_id: 1089 , Total_orders: 3
Customer: Monika Berg, Order_id: 1564 , Total_orders: 3
Customer: Bridgette Guerra, Order_id: 897 , Total_orders: 3
Customer: Bridgette Guerra, Order_id: 1072 , Total_orders: 3
Customer: Bridgette Guerra, Order_id: 1516 , Total_orders: 3
Customer: Cesar Jackson, Order_id: 1200 , Total_orders: 2
Customer: Cesar Jackson, Order_id: 1577 , Total_orders: 2
Customer: Caroll Hays, Order_id: 739 , Total_orders: 2
Customer: Caroll Hays, Order_id: 1599 , Total_orders: 2
Customer: Cleotilde Booth, Order_id: 70 , Total_orders: 3
Customer: Cleotilde Booth, Order_id: 593 , Total_orders: 3
Customer: Cleotilde Booth, Order_id: 1529 , Total_orders: 3
Customer: Gertrud Rhodes, Order_id: 222 , Total_orders: 2
Customer: Gertrud Rhodes, Order_id: 1485 , Total_orders: 2
Customer: Tu Ramirez, Order_id: 1116 , Total_orders: 2
Customer: Tu Ramirez, Order_id: 1501 , Total_orders: 2
Customer: Saturnina Garner, Order_id: 389 , Total_orders: 3
Customer: Saturnina Garner, Order_id: 1521 , Total_orders: 3
Customer: Saturnina Garner, Order_id: 1608 , Total_orders: 3
Customer: Fran Yang, Order_id: 519 , Total_orders: 2
Customer: Fran Yang, Order_id: 1570 , Total_orders: 2
Customer: Diana Guerra, Order_id: 147 , Total_orders: 2
Customer: Diana Guerra, Order_id: 1602 , Total_orders: 2
Customer: Lolita Mosley, Order_id: 778 , Total_orders: 3
Customer: Lolita Mosley, Order_id: 1413 , Total_orders: 3
Customer: Lolita Mosley, Order_id: 1597 , Total_orders: 3
Customer: Pamala Henry, Order_id: 27 , Total_orders: 2
Customer: Pamala Henry, Order_id: 1560 , Total_orders: 2
Customer: Damien Dorsey, Order_id: 694 , Total_orders: 2
Customer: Damien Dorsey, Order_id: 1542 , Total_orders: 2
Customer: Latasha Stanley, Order_id: 286 , Total_orders: 2
Customer: Latasha Stanley, Order_id: 1526 , Total_orders: 2
Customer: Neil Mccall, Order_id: 9 , Total_orders: 2
Customer: Neil Mccall, Order_id: 1565 , Total_orders: 2
Customer: Elinore Aguilar, Order_id: 391 , Total_orders: 3
Customer: Elinore Aguilar, Order_id: 556 , Total_orders: 3
Customer: Elinore Aguilar, Order_id: 1515 , Total_orders: 3
Customer: Alica Hunter, Order_id: 543 , Total_orders: 2
Customer: Alica Hunter, Order_id: 1481 , Total_orders: 2
Customer: Tenisha Lyons, Order_id: 1390 , Total_orders: 2
Customer: Tenisha Lyons, Order_id: 1558 , Total_orders: 2
Customer: Bobbie Foster, Order_id: 549 , Total_orders: 3
Customer: Bobbie Foster, Order_id: 673 , Total_orders: 3
Customer: Bobbie Foster, Order_id: 1493 , Total_orders: 3
Customer: Kanesha Vega, Order_id: 240 , Total_orders: 2
Customer: Kanesha Vega, Order_id: 1561 , Total_orders: 2
Customer: Lorrie Becker, Order_id: 252 , Total_orders: 3
Customer: Lorrie Becker, Order_id: 885 , Total_orders: 3
Customer: Lorrie Becker, Order_id: 1520 , Total_orders: 3
Customer: Tommie Melton, Order_id: 424 , Total_orders: 2
Customer: Tommie Melton, Order_id: 1545 , Total_orders: 2
Customer: Jayne Kirkland, Order_id: 924 , Total_orders: 3
Customer: Jayne Kirkland, Order_id: 1325 , Total_orders: 3
Customer: Jayne Kirkland, Order_id: 1512 , Total_orders: 3
Customer: Katelin Kennedy, Order_id: 1130 , Total_orders: 2
Customer: Katelin Kennedy, Order_id: 1494 , Total_orders: 2
Customer: Tomasa Carson, Order_id: 1041 , Total_orders: 2
Customer: Tomasa Carson, Order_id: 1551 , Total_orders: 2
Customer: Takako Casey, Order_id: 1360 , Total_orders: 2
Customer: Takako Casey, Order_id: 1595 , Total_orders: 2
Customer: Petronila Norris, Order_id: 420 , Total_orders: 2
Customer: Petronila Norris, Order_id: 1566 , Total_orders: 2
Customer: Melanie Hayes, Order_id: 937 , Total_orders: 2
Customer: Melanie Hayes, Order_id: 1552 , Total_orders: 2
Customer: Georgeann Waller, Order_id: 464 , Total_orders: 2
Customer: Georgeann Waller, Order_id: 1603 , Total_orders: 2
Customer: Abby Gamble, Order_id: 1318 , Total_orders: 2
Customer: Abby Gamble, Order_id: 1506 , Total_orders: 2
Customer: Parker Prince, Order_id: 152 , Total_orders: 2
Customer: Parker Prince, Order_id: 1543 , Total_orders: 2
Customer: Keri Bridges, Order_id: 407 , Total_orders: 3
Customer: Keri Bridges, Order_id: 435 , Total_orders: 3
Customer: Keri Bridges, Order_id: 1563 , Total_orders: 3
Customer: Chi Goff, Order_id: 801 , Total_orders: 2
Customer: Chi Goff, Order_id: 1522 , Total_orders: 2
Customer: Ashanti Parks, Order_id: 707 , Total_orders: 2
Customer: Ashanti Parks, Order_id: 1538 , Total_orders: 2
Customer: Sarai Mckee, Order_id: 34 , Total_orders: 2
Customer: Sarai Mckee, Order_id: 1571 , Total_orders: 2
Customer: Zina Bonner, Order_id: 679 , Total_orders: 2
Customer: Zina Bonner, Order_id: 1498 , Total_orders: 2
Customer: Lizzie Joyner, Order_id: 961 , Total_orders: 2
Customer: Lizzie Joyner, Order_id: 1491 , Total_orders: 2
Customer: Tiesha Daniel, Order_id: 327 , Total_orders: 2
Customer: Tiesha Daniel, Order_id: 1502 , Total_orders: 2
Customer: Armand Whitehead, Order_id: 129 , Total_orders: 2
Customer: Armand Whitehead, Order_id: 1486 , Total_orders: 2
Customer: Teofila Fischer, Order_id: 1283 , Total_orders: 2
Customer: Teofila Fischer, Order_id: 1507 , Total_orders: 2
Customer: Lissa Vargas, Order_id: 128 , Total_orders: 2
Customer: Lissa Vargas, Order_id: 1495 , Total_orders: 2
Customer: Yan Mcgowan, Order_id: 747 , Total_orders: 2
Customer: Yan Mcgowan, Order_id: 1514 , Total_orders: 2
Customer: Titus Bullock, Order_id: 418 , Total_orders: 2
Customer: Titus Bullock, Order_id: 1562 , Total_orders: 2
Customer: Arvilla Osborn, Order_id: 1229 , Total_orders: 2
Customer: Arvilla Osborn, Order_id: 1567 , Total_orders: 2
Customer: Marjorie Logan, Order_id: 561 , Total_orders: 2
Customer: Marjorie Logan, Order_id: 1600 , Total_orders: 2
Customer: Marvin Mullins, Order_id: 12 , Total_orders: 2
Customer: Marvin Mullins, Order_id: 1546 , Total_orders: 2
Customer: Tena Cruz, Order_id: 1369 , Total_orders: 2
Customer: Tena Cruz, Order_id: 1508 , Total_orders: 2
Customer: Corrina Sawyer, Order_id: 934 , Total_orders: 2
Customer: Corrina Sawyer, Order_id: 1578 , Total_orders: 2
Customer: Sharyn Hopkins, Order_id: 6 , Total_orders: 2
Customer: Sharyn Hopkins, Order_id: 1482 , Total_orders: 2
Customer: Letitia Franco, Order_id: 804 , Total_orders: 1
Customer: Floretta Higgins, Order_id: 604 , Total_orders: 1
Customer: Louanne Martin, Order_id: 867 , Total_orders: 2
Customer: Louanne Martin, Order_id: 1517 , Total_orders: 2
Customer: Violet Valenzuela, Order_id: 190 , Total_orders: 1
Customer: Carie Kidd, Order_id: 169 , Total_orders: 1
Customer: Kellie Franco, Order_id: 1405 , Total_orders: 1
Customer: Nichelle Howell, Order_id: 448 , Total_orders: 1
Customer: Marisol Goodman, Order_id: 588 , Total_orders: 1
Customer: Sylvie Wilkerson, Order_id: 401 , Total_orders: 1
Customer: Katharina Bates, Order_id: 554 , Total_orders: 2
Customer: Katharina Bates, Order_id: 1579 , Total_orders: 2
Customer: Marget Hodge, Order_id: 207 , Total_orders: 1
Customer: Raul Melendez, Order_id: 1066 , Total_orders: 1
Customer: Cecil Hopper, Order_id: 258 , Total_orders: 1
Customer: Shae Hickman, Order_id: 1297 , Total_orders: 1
Customer: Monica Sears, Order_id: 1411 , Total_orders: 2
Customer: Monica Sears, Order_id: 1584 , Total_orders: 2
Customer: Ollie Zimmerman, Order_id: 1252 , Total_orders: 2
Customer: Ollie Zimmerman, Order_id: 1530 , Total_orders: 2
Customer: Shila White, Order_id: 516 , Total_orders: 1
Customer: Yuk Vega, Order_id: 1475 , Total_orders: 1
Customer: Eliana Silva, Order_id: 1264 , Total_orders: 1
Customer: Thalia Horne, Order_id: 1472 , Total_orders: 1
Customer: Rey Lindsay, Order_id: 1370 , Total_orders: 1
Customer: Merlene Vinson, Order_id: 531 , Total_orders: 3
Customer: Merlene Vinson, Order_id: 1047 , Total_orders: 3
Customer: Merlene Vinson, Order_id: 1539 , Total_orders: 3
Customer: Dacia William, Order_id: 158 , Total_orders: 2
Customer: Dacia William, Order_id: 173 , Total_orders: 2
Customer: Le Wood, Order_id: 617 , Total_orders: 1
Customer: Thalia Dillard, Order_id: 741 , Total_orders: 2
Customer: Thalia Dillard, Order_id: 1606 , Total_orders: 2
Customer: Luz House, Order_id: 907 , Total_orders: 2
Customer: Luz House, Order_id: 1499 , Total_orders: 2
Customer: Lucy Woods, Order_id: 177 , Total_orders: 2
Customer: Lucy Woods, Order_id: 1557 , Total_orders: 2
Customer: Shena Carter, Order_id: 1364 , Total_orders: 1
Customer: Robena Hill, Order_id: 1280 , Total_orders: 2
Customer: Robena Hill, Order_id: 1605 , Total_orders: 2
Customer: Jeni Booker, Order_id: 738 , Total_orders: 2
Customer: Jeni Booker, Order_id: 1574 , Total_orders: 2
Customer: Herlinda Stone, Order_id: 1021 , Total_orders: 1
Customer: Lavina Dejesus, Order_id: 1425 , Total_orders: 1
Customer: Erlinda Nielsen, Order_id: 197 , Total_orders: 1
Customer: Terrance Lynn, Order_id: 1284 , Total_orders: 1
Customer: Walton Dejesus, Order_id: 938 , Total_orders: 1
Customer: Wes Stanton, Order_id: 626 , Total_orders: 1
Customer: Tanesha Hampton, Order_id: 618 , Total_orders: 1
Customer: Boyd Irwin, Order_id: 372 , Total_orders: 1
Customer: Delbert Wilkins, Order_id: 287 , Total_orders: 1
Customer: Brianna Moss, Order_id: 184 , Total_orders: 1
Customer: Dorthey Jackson, Order_id: 770 , Total_orders: 2
Customer: Dorthey Jackson, Order_id: 1614 , Total_orders: 2
Customer: Sarita Parks, Order_id: 1346 , Total_orders: 2
Customer: Sarita Parks, Order_id: 1615 , Total_orders: 2
Customer: Shonta Mercer, Order_id: 743 , Total_orders: 1
Customer: Jone Bernard, Order_id: 944 , Total_orders: 2
Customer: Jone Bernard, Order_id: 1590 , Total_orders: 2
Customer: Wanita Davenport, Order_id: 1461 , Total_orders: 1
Customer: Cleopatra Tate, Order_id: 1055 , Total_orders: 1
Customer: Ramiro Byers, Order_id: 766 , Total_orders: 1
Customer: Nicholas Vazquez, Order_id: 950 , Total_orders: 1
Customer: Janae Doyle, Order_id: 1121 , Total_orders: 1
Customer: Hans Price, Order_id: 395 , Total_orders: 1
Customer: Miquel Neal, Order_id: 249 , Total_orders: 1
Customer: Stefany Potter, Order_id: 1399 , Total_orders: 1
Customer: Bernetta Marquez, Order_id: 732 , Total_orders: 1
Customer: Julee Woodard, Order_id: 500 , Total_orders: 1
Customer: Meredith Bryan, Order_id: 439 , Total_orders: 1
Customer: Weldon Michael, Order_id: 250 , Total_orders: 1
Customer: Joesph Delacruz, Order_id: 60 , Total_orders: 2
Customer: Joesph Delacruz, Order_id: 1500 , Total_orders: 2
Customer: Katherina Odom, Order_id: 1467 , Total_orders: 1
Customer: Laraine Robbins, Order_id: 429 , Total_orders: 2
Customer: Laraine Robbins, Order_id: 810 , Total_orders: 2
Customer: Jenise Preston, Order_id: 796 , Total_orders: 1
Customer: Lory Page, Order_id: 513 , Total_orders: 1
Customer: Charlyn Cantrell, Order_id: 308 , Total_orders: 1
Customer: Carola Rodriquez, Order_id: 224 , Total_orders: 2
Customer: Carola Rodriquez, Order_id: 1585 , Total_orders: 2
Customer: Alane Kennedy, Order_id: 291 , Total_orders: 1
Customer: Regina Burns, Order_id: 282 , Total_orders: 1
Customer: Omer Estrada, Order_id: 579 , Total_orders: 1
Customer: Crystle Gilliam, Order_id: 1030 , Total_orders: 1
Customer: Kam Wilder, Order_id: 858 , Total_orders: 1
Customer: Margert Stevens, Order_id: 632 , Total_orders: 1
Customer: Tomika Larson, Order_id: 37 , Total_orders: 1
Customer: Jeromy Burch, Order_id: 1275 , Total_orders: 2
Customer: Jeromy Burch, Order_id: 1591 , Total_orders: 2
Customer: Lena Mills, Order_id: 744 , Total_orders: 1
Customer: Loreta Johnston, Order_id: 945 , Total_orders: 1
Customer: Nettie Mcdaniel, Order_id: 1017 , Total_orders: 1
Customer: Karla Kirk, Order_id: 432 , Total_orders: 2
Customer: Karla Kirk, Order_id: 1547 , Total_orders: 2
Customer: Regine Gonzales, Order_id: 142 , Total_orders: 2
Customer: Regine Gonzales, Order_id: 1548 , Total_orders: 2
Customer: Miriam Baker, Order_id: 890 , Total_orders: 1
Customer: Jeanie Kirkland, Order_id: 987 , Total_orders: 2
Customer: Jeanie Kirkland, Order_id: 1554 , Total_orders: 2
Customer: Marquerite Dawson, Order_id: 712 , Total_orders: 1
Customer: Babara Ochoa, Order_id: 1013 , Total_orders: 1
Customer: Nova Hess, Order_id: 4 , Total_orders: 2
Customer: Nova Hess, Order_id: 1518 , Total_orders: 2
Customer: Carley Reynolds, Order_id: 392 , Total_orders: 2
Customer: Carley Reynolds, Order_id: 1586 , Total_orders: 2
Customer: Carissa Foreman, Order_id: 854 , Total_orders: 1
Customer: Genoveva Tyler, Order_id: 572 , Total_orders: 1
Customer: Deane Sears, Order_id: 903 , Total_orders: 1
Customer: Karey Steele, Order_id: 1477 , Total_orders: 1
Customer: Olevia Pitts, Order_id: 283 , Total_orders: 2
Customer: Olevia Pitts, Order_id: 1488 , Total_orders: 2
Customer: Jenniffer Bullock, Order_id: 1060 , Total_orders: 1
Customer: Jeniffer Ratliff, Order_id: 187 , Total_orders: 1
Customer: Klara Stanley, Order_id: 736 , Total_orders: 1
Customer: Morton Lee, Order_id: 1045 , Total_orders: 1
Customer: Ken Charles, Order_id: 1191 , Total_orders: 1
Customer: Hedwig Paul, Order_id: 362 , Total_orders: 2
Customer: Hedwig Paul, Order_id: 1540 , Total_orders: 2
Customer: Sharla Flynn, Order_id: 909 , Total_orders: 2

### Task 5: Retrieve products with stock quantities less than 50.

In [53]:
sql_query_3 = """SELECT p.product_name, p.product_id, s.quantity
FROM products p
JOIN stocks s ON p.product_id = s.product_id
WHERE s.quantity < 50;"""

cursor.execute(sql_query_3)
output3 = cursor.fetchall()

for row in output3:
    print(f"Product: {row[0]}, product_id: {row[1]} , Quantity: {row[2]}")

Product: Trek 820 - 2016, product_id: 1 , Quantity: 27
Product: Trek 820 - 2016, product_id: 1 , Quantity: 14
Product: Trek 820 - 2016, product_id: 1 , Quantity: 14
Product: Ritchey Timberwolf Frameset - 2016, product_id: 2 , Quantity: 5
Product: Ritchey Timberwolf Frameset - 2016, product_id: 2 , Quantity: 16
Product: Ritchey Timberwolf Frameset - 2016, product_id: 2 , Quantity: 24
Product: Surly Wednesday Frameset - 2016, product_id: 3 , Quantity: 6
Product: Surly Wednesday Frameset - 2016, product_id: 3 , Quantity: 28
Product: Surly Wednesday Frameset - 2016, product_id: 3 , Quantity: 0
Product: Trek Fuel EX 8 29 - 2016, product_id: 4 , Quantity: 23
Product: Trek Fuel EX 8 29 - 2016, product_id: 4 , Quantity: 2
Product: Trek Fuel EX 8 29 - 2016, product_id: 4 , Quantity: 11
Product: Heller Shagamaw Frame - 2016, product_id: 5 , Quantity: 22
Product: Heller Shagamaw Frame - 2016, product_id: 5 , Quantity: 1
Product: Heller Shagamaw Frame - 2016, product_id: 5 , Quantity: 3
Product: Surly Ice Cream Truck Frameset - 2016, product_id: 6 , Quantity: 0
Product: Surly Ice Cream Truck Frameset - 2016, product_id: 6 , Quantity: 11
Product: Surly Ice Cream Truck Frameset - 2016, product_id: 6 , Quantity: 27
Product: Trek Slash 8 27.5 - 2016, product_id: 7 , Quantity: 8
Product: Trek Slash 8 27.5 - 2016, product_id: 7 , Quantity: 8
Product: Trek Slash 8 27.5 - 2016, product_id: 7 , Quantity: 12
Product: Trek Remedy 29 Carbon Frameset - 2016, product_id: 8 , Quantity: 0
Product: Trek Remedy 29 Carbon Frameset - 2016, product_id: 8 , Quantity: 1
Product: Trek Remedy 29 Carbon Frameset - 2016, product_id: 8 , Quantity: 12
Product: Trek Conduit+ - 2016, product_id: 9 , Quantity: 11
Product: Trek Conduit+ - 2016, product_id: 9 , Quantity: 17
Product: Trek Conduit+ - 2016, product_id: 9 , Quantity: 23
Product: Surly Straggler - 2016, product_id: 10 , Quantity: 15
Product: Surly Straggler - 2016, product_id: 10 , Quantity: 13
Product: Surly Straggler - 2016, product_id: 10 , Quantity: 21
Product: Surly Straggler 650b - 2016, product_id: 11 , Quantity: 8
Product: Surly Straggler 650b - 2016, product_id: 11 , Quantity: 21
Product: Surly Straggler 650b - 2016, product_id: 11 , Quantity: 30
Product: Electra Townie Original 21D - 2016, product_id: 12 , Quantity: 16
Product: Electra Townie Original 21D - 2016, product_id: 12 , Quantity: 2
Product: Electra Townie Original 21D - 2016, product_id: 12 , Quantity: 30
Product: Electra Cruiser 1 (24-Inch) - 2016, product_id: 13 , Quantity: 13
Product: Electra Cruiser 1 (24-Inch) - 2016, product_id: 13 , Quantity: 1
Product: Electra Cruiser 1 (24-Inch) - 2016, product_id: 13 , Quantity: 19
Product: Electra Girl's Hawaii 1 (16-inch) - 2015/2016, product_id: 14 , Quantity: 8
Product: Electra Girl's Hawaii 1 (16-inch) - 2015/2016, product_id: 14 , Quantity: 18
Product: Electra Girl's Hawaii 1 (16-inch) - 2015/2016, product_id: 14 , Quantity: 4
Product: Electra Moto 1 - 2016, product_id: 15 , Quantity: 3
Product: Electra Moto 1 - 2016, product_id: 15 , Quantity: 6
Product: Electra Moto 1 - 2016, product_id: 15 , Quantity: 22
Product: Electra Townie Original 7D EQ - 2016, product_id: 16 , Quantity: 4
Product: Electra Townie Original 7D EQ - 2016, product_id: 16 , Quantity: 20
Product: Electra Townie Original 7D EQ - 2016, product_id: 16 , Quantity: 19
Product: Pure Cycles Vine 8-Speed - 2016, product_id: 17 , Quantity: 2
Product: Pure Cycles Vine 8-Speed - 2016, product_id: 17 , Quantity: 3
Product: Pure Cycles Vine 8-Speed - 2016, product_id: 17 , Quantity: 22
Product: Pure Cycles Western 3-Speed - Women's - 2015/2016, product_id: 18 , Quantity: 16
Product: Pure Cycles Western 3-Speed - Women's - 2015/2016, product_id: 18 , Quantity: 13
Product: Pure Cycles Western 3-Speed - Women's - 2015/2016, product_id: 18 , Quantity: 5
Product: Pure Cycles William 3-Speed - 2016, product_id: 19 , Quantity: 4
Product: Pure Cycles William 3-Speed - 2016, product_id: 19 , Quantity: 15
Product: Pure Cycles William 3-Speed - 2016, product_id: 19 , Quantity: 24
Product: Electra Townie Original 7D EQ - Women's - 2016, product_id: 20 , Quantity: 26
Product: Electra Townie Original 7D EQ - Women's - 2016, product_id: 20 , Quantity: 20
Product: Electra Townie Original 7D EQ - Women's - 2016, product_id: 20 , Quantity: 19
Product: Electra Cruiser 1 (24-Inch) - 2016, product_id: 21 , Quantity: 24
Product: Electra Cruiser 1 (24-Inch) - 2016, product_id: 21 , Quantity: 16
Product: Electra Cruiser 1 (24-Inch) - 2016, product_id: 21 , Quantity: 8
Product: Electra Girl's Hawaii 1 (16-inch) - 2015/2016, product_id: 22 , Quantity: 29
Product: Electra Girl's Hawaii 1 (16-inch) - 2015/2016, product_id: 22 , Quantity: 0
Product: Electra Girl's Hawaii 1 (16-inch) - 2015/2016, product_id: 22 , Quantity: 20
Product: Electra Girl's Hawaii 1 (20-inch) - 2015/2016, product_id: 23 , Quantity: 9
Product: Electra Girl's Hawaii 1 (20-inch) - 2015/2016, product_id: 23 , Quantity: 12
Product: Electra Girl's Hawaii 1 (20-inch) - 2015/2016, product_id: 23 , Quantity: 8
Product: Electra Townie Original 21D - 2016, product_id: 24 , Quantity: 10
Product: Electra Townie Original 21D - 2016, product_id: 24 , Quantity: 16
Product: Electra Townie Original 21D - 2016, product_id: 24 , Quantity: 18
Product: Electra Townie Original 7D - 2015/2016, product_id: 25 , Quantity: 10
Product: Electra Townie Original 7D - 2015/2016, product_id: 25 , Quantity: 18
Product: Electra Townie Original 7D - 2015/2016, product_id: 25 , Quantity: 15
Product: Electra Townie Original 7D EQ - 2016, product_id: 26 , Quantity: 16
Product: Electra Townie Original 7D EQ - 2016, product_id: 26 , Quantity: 2
Product: Electra Townie Original 7D EQ - 2016, product_id: 26 , Quantity: 27
Product: Surly Big Dummy Frameset - 2017, product_id: 27 , Quantity: 21
Product: Surly Big Dummy Frameset - 2017, product_id: 27 , Quantity: 10
Product: Surly Big Dummy Frameset - 2017, product_id: 27 , Quantity: 21
Product: Surly Karate Monkey 27.5+ Frameset - 2017, product_id: 28 , Quantity: 20
Product: Surly Karate Monkey 27.5+ Frameset - 2017, product_id: 28 , Quantity: 25
Product: Surly Karate Monkey 27.5+ Frameset - 2017, product_id: 28 , Quantity: 20
Product: Trek X-Caliber 8 - 2017, product_id: 29 , Quantity: 13
Product: Trek X-Caliber 8 - 2017, product_id: 29 , Quantity: 29
Product: Trek X-Caliber 8 - 2017, product_id: 29 , Quantity: 11
Product: Surly Ice Cream Truck Frameset - 2017, product_id: 30 , Quantity: 30
Product: Surly Ice Cream Truck Frameset - 2017, product_id: 30 , Quantity: 17
Product: Surly Ice Cream Truck Frameset - 2017, product_id: 30 , Quantity: 23
Product: Surly Wednesday - 2017, product_id: 31 , Quantity: 2
Product: Surly Wednesday - 2017, product_id: 31 , Quantity: 10
Product: Surly Wednesday - 2017, product_id: 31 , Quantity: 10
Product: Trek Farley Alloy Frameset - 2017, product_id: 32 , Quantity: 0
Product: Trek Farley Alloy Frameset - 2017, product_id: 32 , Quantity: 13
Product: Trek Farley Alloy Frameset - 2017, product_id: 32 , Quantity: 14
Product: Surly Wednesday Frameset - 2017, product_id: 33 , Quantity: 10
Product: Surly Wednesday Frameset - 2017, product_id: 33 , Quantity: 8
Product: Surly Wednesday Frameset - 2017, product_id: 33 , Quantity: 14
Product: Trek Session DH 27.5 Carbon Frameset - 2017, product_id: 34 , Quantity: 2
Product: Trek Session DH 27.5 Carbon Frameset - 2017, product_id: 34 , Quantity: 24
Product: Trek Session DH 27.5 Carbon Frameset - 2017, product_id: 34 , Quantity: 6
Product: Sun Bicycles Spider 3i - 2017, product_id: 35 , Quantity: 18
Product: Sun Bicycles Spider 3i - 2017, product_id: 35 , Quantity: 25
Product: Sun Bicycles Spider 3i - 2017, product_id: 35 , Quantity: 3
Product: Surly Troll Frameset - 2017, product_id: 36 , Quantity: 26
Product: Surly Troll Frameset - 2017, product_id: 36 , Quantity: 15
Product: Surly Troll Frameset - 2017, product_id: 36 , Quantity: 28
Product: Haro Flightline One ST - 2017, product_id: 37 , Quantity: 12
Product: Haro Flightline One ST - 2017, product_id: 37 , Quantity: 5
Product: Haro Flightline One ST - 2017, product_id: 37 , Quantity: 30
Product: Haro Flightline Two 26 Plus - 2017, product_id: 38 , Quantity: 13
Product: Haro Flightline Two 26 Plus - 2017, product_id: 38 , Quantity: 18
Product: Haro Flightline Two 26 Plus - 2017, product_id: 38 , Quantity: 23
Product: Trek Stache 5 - 2017, product_id: 39 , Quantity: 2
Product: Trek Stache 5 - 2017, product_id: 39 , Quantity: 28
Product: Trek Stache 5 - 2017, product_id: 39 , Quantity: 22
Product: Trek Fuel EX 9.8 29 - 2017, product_id: 40 , Quantity: 24
Product: Trek Fuel EX 9.8 29 - 2017, product_id: 40 , Quantity: 15
Product: Trek Fuel EX 9.8 29 - 2017, product_id: 40 , Quantity: 2
Product: Haro Shift R3 - 2017, product_id: 41 , Quantity: 10
Product: Haro Shift R3 - 2017, product_id: 41 , Quantity: 6
Product: Haro Shift R3 - 2017, product_id: 41 , Quantity: 25
Product: Trek Fuel EX 5 27.5 Plus - 2017, product_id: 42 , Quantity: 0
Product: Trek Fuel EX 5 27.5 Plus - 2017, product_id: 42 , Quantity: 16
Product: Trek Fuel EX 5 27.5 Plus - 2017, product_id: 42 , Quantity: 9
Product: Trek Fuel EX 9.8 27.5 Plus - 2017, product_id: 43 , Quantity: 2
Product: Trek Fuel EX 9.8 27.5 Plus - 2017, product_id: 43 , Quantity: 2
Product: Trek Fuel EX 9.8 27.5 Plus - 2017, product_id: 43 , Quantity: 26
Product: Haro SR 1.1 - 2017, product_id: 44 , Quantity: 1
Product: Haro SR 1.1 - 2017, product_id: 44 , Quantity: 24
Product: Haro SR 1.1 - 2017, product_id: 44 , Quantity: 26
Product: Haro SR 1.2 - 2017, product_id: 45 , Quantity: 15
Product: Haro SR 1.2 - 2017, product_id: 45 , Quantity: 13
Product: Haro SR 1.2 - 2017, product_id: 45 , Quantity: 1
Product: Haro SR 1.3 - 2017, product_id: 46 , Quantity: 19
Product: Haro SR 1.3 - 2017, product_id: 46 , Quantity: 18
Product: Haro SR 1.3 - 2017, product_id: 46 , Quantity: 16
Product: Trek Remedy 9.8 - 2017, product_id: 47 , Quantity: 21
Product: Trek Remedy 9.8 - 2017, product_id: 47 , Quantity: 0
Product: Trek Remedy 9.8 - 2017, product_id: 47 , Quantity: 14
Product: Trek Emonda S 4 - 2017, product_id: 48 , Quantity: 5
Product: Trek Emonda S 4 - 2017, product_id: 48 , Quantity: 20
Product: Trek Emonda S 4 - 2017, product_id: 48 , Quantity: 2
Product: Trek Domane SL 6 - 2017, product_id: 49 , Quantity: 8
Product: Trek Domane SL 6 - 2017, product_id: 49 , Quantity: 4
Product: Trek Domane SL 6 - 2017, product_id: 49 , Quantity: 4
Product: Trek Silque SLR 7 Women's - 2017, product_id: 50 , Quantity: 29
Product: Trek Silque SLR 7 Women's - 2017, product_id: 50 , Quantity: 7
Product: Trek Silque SLR 7 Women's - 2017, product_id: 50 , Quantity: 25
Product: Trek Silque SLR 8 Women's - 2017, product_id: 51 , Quantity: 2
Product: Trek Silque SLR 8 Women's - 2017, product_id: 51 , Quantity: 8
Product: Trek Silque SLR 8 Women's - 2017, product_id: 51 , Quantity: 2
Product: Surly Steamroller - 2017, product_id: 52 , Quantity: 18
Product: Surly Steamroller - 2017, product_id: 52 , Quantity: 23
Product: Surly Steamroller - 2017, product_id: 52 , Quantity: 8
Product: Surly Ogre Frameset - 2017, product_id: 53 , Quantity: 17
Product: Surly Ogre Frameset - 2017, product_id: 53 , Quantity: 19
Product: Surly Ogre Frameset - 2017, product_id: 53 , Quantity: 6
Product: Trek Domane SL Disc Frameset - 2017, product_id: 54 , Quantity: 11
Product: Trek Domane SL Disc Frameset - 2017, product_id: 54 , Quantity: 6
Product: Trek Domane SL Disc Frameset - 2017, product_id: 54 , Quantity: 13
Product: Trek Domane S 6 - 2017, product_id: 55 , Quantity: 11
Product: Trek Domane S 6 - 2017, product_id: 55 , Quantity: 5
Product: Trek Domane S 6 - 2017, product_id: 55 , Quantity: 5
Product: Trek Domane SLR 6 Disc - 2017, product_id: 56 , Quantity: 15
Product: Trek Domane SLR 6 Disc - 2017, product_id: 56 , Quantity: 20
Product: Trek Domane SLR 6 Disc - 2017, product_id: 56 , Quantity: 19
Product: Trek Emonda S 5 - 2017, product_id: 57 , Quantity: 1
Product: Trek Emonda S 5 - 2017, product_id: 57 , Quantity: 27
Product: Trek Emonda S 5 - 2017, product_id: 57 , Quantity: 9
Product: Trek Madone 9.2 - 2017, product_id: 58 , Quantity: 1
Product: Trek Madone 9.2 - 2017, product_id: 58 , Quantity: 15
Product: Trek Madone 9.2 - 2017, product_id: 58 , Quantity: 27
Product: Trek Domane S 5 Disc - 2017, product_id: 59 , Quantity: 22
Product: Trek Domane S 5 Disc - 2017, product_id: 59 , Quantity: 17
Product: Trek Domane S 5 Disc - 2017, product_id: 59 , Quantity: 0
Product: Sun Bicycles ElectroLite - 2017, product_id: 60 , Quantity: 19
Product: Sun Bicycles ElectroLite - 2017, product_id: 60 , Quantity: 1
Product: Sun Bicycles ElectroLite - 2017, product_id: 60 , Quantity: 7
Product: Trek Powerfly 8 FS Plus - 2017, product_id: 61 , Quantity: 30
Product: Trek Powerfly 8 FS Plus - 2017, product_id: 61 , Quantity: 20
Product: Trek Powerfly 8 FS Plus - 2017, product_id: 61 , Quantity: 28
Product: Trek Boone 7 - 2017, product_id: 62 , Quantity: 21
Product: Trek Boone 7 - 2017, product_id: 62 , Quantity: 4
Product: Trek Boone 7 - 2017, product_id: 62 , Quantity: 4
Product: Trek Boone Race Shop Limited - 2017, product_id: 63 , Quantity: 4
Product: Trek Boone Race Shop Limited - 2017, product_id: 63 , Quantity: 5
Product: Trek Boone Race Shop Limited - 2017, product_id: 63 , Quantity: 8
Product: Electra Townie Original 7D - 2017, product_id: 64 , Quantity: 30
Product: Electra Townie Original 7D - 2017, product_id: 64 , Quantity: 30
Product: Electra Townie Original 7D - 2017, product_id: 64 , Quantity: 22
Product: Sun Bicycles Lil Bolt Type-R - 2017, product_id: 65 , Quantity: 10
Product: Sun Bicycles Lil Bolt Type-R - 2017, product_id: 65 , Quantity: 16
Product: Sun Bicycles Lil Bolt Type-R - 2017, product_id: 65 , Quantity: 1
Product: Sun Bicycles Revolutions 24 - 2017, product_id: 66 , Quantity: 12
Product: Sun Bicycles Revolutions 24 - 2017, product_id: 66 , Quantity: 22
Product: Sun Bicycles Revolutions 24 - 2017, product_id: 66 , Quantity: 3
Product: Sun Bicycles Revolutions 24 - Girl's - 2017, product_id: 67 , Quantity: 19
Product: Sun Bicycles Revolutions 24 - Girl's - 2017, product_id: 67 , Quantity: 8
Product: Sun Bicycles Revolutions 24 - Girl's - 2017, product_id: 67 , Quantity: 6
Product: Sun Bicycles Cruz 3 - 2017, product_id: 68 , Quantity: 30
Product: Sun Bicycles Cruz 3 - 2017, product_id: 68 , Quantity: 23
Product: Sun Bicycles Cruz 3 - 2017, product_id: 68 , Quantity: 18
Product: Sun Bicycles Cruz 7 - 2017, product_id: 69 , Quantity: 4
Product: Sun Bicycles Cruz 7 - 2017, product_id: 69 , Quantity: 22
Product: Sun Bicycles Cruz 7 - 2017, product_id: 69 , Quantity: 29
Product: Electra Amsterdam Original 3i - 2015/2017, product_id: 70 , Quantity: 3
Product: Electra Amsterdam Original 3i - 2015/2017, product_id: 70 , Quantity: 6
Product: Electra Amsterdam Original 3i - 2015/2017, product_id: 70 , Quantity: 2
Product: Sun Bicycles Atlas X-Type - 2017, product_id: 71 , Quantity: 25
Product: Sun Bicycles Atlas X-Type - 2017, product_id: 71 , Quantity: 30
Product: Sun Bicycles Atlas X-Type - 2017, product_id: 71 , Quantity: 13
Product: Sun Bicycles Biscayne Tandem 7 - 2017, product_id: 72 , Quantity: 9
Product: Sun Bicycles Biscayne Tandem 7 - 2017, product_id: 72 , Quantity: 1
Product: Sun Bicycles Biscayne Tandem 7 - 2017, product_id: 72 , Quantity: 6
Product: Sun Bicycles Brickell Tandem 7 - 2017, product_id: 73 , Quantity: 7
Product: Sun Bicycles Brickell Tandem 7 - 2017, product_id: 73 , Quantity: 20
Product: Sun Bicycles Brickell Tandem 7 - 2017, product_id: 73 , Quantity: 3
Product: Electra Cruiser Lux 1 - 2017, product_id: 74 , Quantity: 9
Product: Electra Cruiser Lux 1 - 2017, product_id: 74 , Quantity: 23
Product: Electra Cruiser Lux 1 - 2017, product_id: 74 , Quantity: 17
Product: Electra Cruiser Lux Fat Tire 1 Ladies - 2017, product_id: 75 , Quantity: 23
Product: Electra Cruiser Lux Fat Tire 1 Ladies - 2017, product_id: 75 , Quantity: 11
Product: Electra Cruiser Lux Fat Tire 1 Ladies - 2017, product_id: 75 , Quantity: 29
Product: Electra Girl's Hawaii 1 16" - 2017, product_id: 76 , Quantity: 15
Product: Electra Girl's Hawaii 1 16" - 2017, product_id: 76 , Quantity: 20
Product: Electra Girl's Hawaii 1 16" - 2017, product_id: 76 , Quantity: 23
Product: Electra Glam Punk 3i Ladies' - 2017, product_id: 77 , Quantity: 16
Product: Electra Glam Punk 3i Ladies' - 2017, product_id: 77 , Quantity: 25
Product: Electra Glam Punk 3i Ladies' - 2017, product_id: 77 , Quantity: 23
Product: Sun Bicycles Biscayne Tandem CB - 2017, product_id: 78 , Quantity: 13
Product: Sun Bicycles Biscayne Tandem CB - 2017, product_id: 78 , Quantity: 4
Product: Sun Bicycles Biscayne Tandem CB - 2017, product_id: 78 , Quantity: 19
Product: Sun Bicycles Boardwalk (24-inch Wheels) - 2017, product_id: 79 , Quantity: 13
Product: Sun Bicycles Boardwalk (24-inch Wheels) - 2017, product_id: 79 , Quantity: 29
Product: Sun Bicycles Boardwalk (24-inch Wheels) - 2017, product_id: 79 , Quantity: 29
Product: Sun Bicycles Brickell Tandem CB - 2017, product_id: 80 , Quantity: 11
Product: Sun Bicycles Brickell Tandem CB - 2017, product_id: 80 , Quantity: 27
Product: Sun Bicycles Brickell Tandem CB - 2017, product_id: 80 , Quantity: 22
Product: Electra Amsterdam Fashion 7i Ladies' - 2017, product_id: 81 , Quantity: 25
Product: Electra Amsterdam Fashion 7i Ladies' - 2017, product_id: 81 , Quantity: 19
Product: Electra Amsterdam Fashion 7i Ladies' - 2017, product_id: 81 , Quantity: 18
Product: Electra Amsterdam Original 3i Ladies' - 2017, product_id: 82 , Quantity: 1
Product: Electra Amsterdam Original 3i Ladies' - 2017, product_id: 82 , Quantity: 4
Product: Electra Amsterdam Original 3i Ladies' - 2017, product_id: 82 , Quantity: 7
Product: Trek Boy's Kickster - 2015/2017, product_id: 83 , Quantity: 13
Product: Trek Boy's Kickster - 2015/2017, product_id: 83 , Quantity: 21
Product: Trek Boy's Kickster - 2015/2017, product_id: 83 , Quantity: 23
Product: Sun Bicycles Lil Kitt'n - 2017, product_id: 84 , Quantity: 11
Product: Sun Bicycles Lil Kitt'n - 2017, product_id: 84 , Quantity: 22
Product: Sun Bicycles Lil Kitt'n - 2017, product_id: 84 , Quantity: 15
Product: Haro Downtown 16 - 2017, product_id: 85 , Quantity: 23
Product: Haro Downtown 16 - 2017, product_id: 85 , Quantity: 6
Product: Haro Downtown 16 - 2017, product_id: 85 , Quantity: 15
Product: Trek Girl's Kickster - 2017, product_id: 86 , Quantity: 19
Product: Trek Girl's Kickster - 2017, product_id: 86 , Quantity: 24
Product: Trek Girl's Kickster - 2017, product_id: 86 , Quantity: 27
Product: Trek Precaliber 12 Boys - 2017, product_id: 87 , Quantity: 27
Product: Trek Precaliber 12 Boys - 2017, product_id: 87 , Quantity: 14
Product: Trek Precaliber 12 Boys - 2017, product_id: 87 , Quantity: 16
Product: Trek Precaliber 12 Girls - 2017, product_id: 88 , Quantity: 7
Product: Trek Precaliber 12 Girls - 2017, product_id: 88 , Quantity: 8
Product: Trek Precaliber 12 Girls - 2017, product_id: 88 , Quantity: 28
Product: Trek Precaliber 16 Boys - 2017, product_id: 89 , Quantity: 9
Product: Trek Precaliber 16 Boys - 2017, product_id: 89 , Quantity: 8
Product: Trek Precaliber 16 Boys - 2017, product_id: 89 , Quantity: 22
Product: Trek Precaliber 16 Girls - 2017, product_id: 90 , Quantity: 4
Product: Trek Precaliber 16 Girls - 2017, product_id: 90 , Quantity: 26
Product: Trek Precaliber 16 Girls - 2017, product_id: 90 , Quantity: 9
Product: Trek Precaliber 24 (21-Speed) - Girls - 2017, product_id: 91 , Quantity: 8
Product: Trek Precaliber 24 (21-Speed) - Girls - 2017, product_id: 91 , Quantity: 0
Product: Trek Precaliber 24 (21-Speed) - Girls - 2017, product_id: 91 , Quantity: 8
Product: Haro Shredder 20 - 2017, product_id: 92 , Quantity: 0
Product: Haro Shredder 20 - 2017, product_id: 92 , Quantity: 22
Product: Haro Shredder 20 - 2017, product_id: 92 , Quantity: 28
Product: Haro Shredder 20 Girls - 2017, product_id: 93 , Quantity: 22
Product: Haro Shredder 20 Girls - 2017, product_id: 93 , Quantity: 22

---

## Level 3: Advanced â€“ Complex Joins and Subqueries
(using Pandas read_sql)

### Task 1: Retrieve the Top 5 Products with the Highest Total Sales Revenue

In [76]:
# kindly note that I used the discount column to calculate the actual revenue
top_five = pd.read_sql("""SELECT p. product_id, p.product_name, sum(o.list_price * o.quantity * (1-o.discount)) As Total_Revenue
                        FROM products p
                        Join order_items o ON p.product_id = o.product_id
                        Group by p.product_id
                        Order by Total_Revenue DESC
                        Limit 5;""", db_connection)
top_five

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\4022074590.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  top_five = pd.read_sql("""SELECT p. product_id, p.product_name, sum(o.list_price * o.quantity * (1-o.discount)) As Total_Revenue

   product_id                   product_name  Total_Revenue
0           7       Trek Slash 8 27.5 - 2016    555558.6111
1           9           Trek Conduit+ - 2016    389248.7025
2           4       Trek Fuel EX 8 29 - 2016    368472.7294
3          11    Surly Straggler 650b - 2016    226765.5510
4          56  Trek Domane SLR 6 Disc - 2017    211584.6153

### Task 2: Find the Customers Who Placed the Most Orders in June, November 2018

In [94]:
customers_jun_nov = pd.read_sql("""SELECT CONCAT(c.first_name, " ", c.last_name) As Full_name, Count(o.order_id) As No_of_orders, o.order_date
                                from customers c
                                Join orders o On c.customer_id = o.customer_id 
                                Where o.order_date Between '2018-06-01' AND '2018-06-30'
                                Or o.order_date Between '2018-11-01' AND '2018-11-30'
                                Group by o.order_date
                                Order by No_of_orders""", db_connection)
customers_jun_nov

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\1763664759.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers_jun_nov = pd.read_sql("""SELECT CONCAT(c.first_name, " ", c.last_name) As Full_name, Count(o.order_id) As No_of_orders, o.order_date

         Full_name  No_of_orders  order_date
0     Latasha Hays             1  2018-06-17
1  Dorthey Jackson             1  2018-11-28
2      Debra Burks             1  2018-11-18

### Task 3: List All Stores with Their Total Stock Quantities for All Products

In [59]:
stores = pd.read_sql("""SELECT s.store_id, s.store_name, ss.product_id, sum(ss.quantity) AS total_stock
                        from stores s
                        Join stocks ss On s.store_id = ss.store_id 
                        Group by ss.store_id
                        order by total_stock DESC""", db_connection)
stores

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\1360404376.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  stores = pd.read_sql("""SELECT s.store_id, s.store_name, ss.product_id, sum(ss.quantity) AS total_stock

   store_id        store_name  product_id  total_stock
0         3     Rowlett Bikes           1       4620.0
1         1  Santa Cruz Bikes           1       4532.0
2         2     Baldwin Bikes           1       4359.0

### Task 4: Retrieve Staff Members Who Work at Stores Located in a Specific State
California (CA) , New York (NY) , Texas (TX)

In [61]:
staff_CA = pd.read_sql("""SELECT st.staff_id, CONCAT(st.first_name, " ", st.last_name) as Full_Name, s.state
                        from staffs st
                        Join stores s On st.store_id = s.store_id 
                        Where s.state = 'CA'""", db_connection)
staff_CA

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\1174013937.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  staff_CA = pd.read_sql("""SELECT st.staff_id, CONCAT(st.first_name, " ", st.last_name) as Full_Name, s.state

   staff_id        Full_Name state
0         1  Fabiola Jackson    CA
1         2  Mireya Copeland    CA
2         3    Genna Serrano    CA
3         4   Virgie Wiggins    CA

In [62]:
staff_NY = pd.read_sql("""SELECT st.staff_id, CONCAT(st.first_name, " ", st.last_name) as Full_Name, s.state
                        from staffs st
                        Join stores s On st.store_id = s.store_id 
                        Where s.state = 'NY'""", db_connection)
staff_NY

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\426195965.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  staff_NY = pd.read_sql("""SELECT st.staff_id, CONCAT(st.first_name, " ", st.last_name) as Full_Name, s.state

   staff_id        Full_Name state
0         5   Jannette David    NY
1         6  Marcelene Boyer    NY
2         7    Venita Daniel    NY

In [63]:
staff_TX = pd.read_sql("""SELECT st.staff_id, CONCAT(st.first_name, " ", st.last_name) as Full_Name, s.state
                        from staffs st
                        Join stores s On st.store_id = s.store_id 
                        Where s.state = 'TX'""", db_connection)
staff_TX

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\917236622.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  staff_TX = pd.read_sql("""SELECT st.staff_id, CONCAT(st.first_name, " ", st.last_name) as Full_Name, s.state

   staff_id           Full_Name state
0         8         Kali Vargas    TX
1         9       Layla Terrell    TX
2        10  Bernardine Houston    TX

### Task 5: Identify the Categories of Products with the Highest Total Revenue

In [78]:
# kindly note that I used the discount column to calculate the actual revenue
category = pd.read_sql(""" SELECT sum(o.list_price * o.quantity * (1-o.discount)) As Total_Revenue , ct.category_id,
                        ct.category_name 
                        from products p
                        Join order_items o ON p.product_id = o.product_id
                        LEFT Join categories ct ON p.category_id = ct.category_id 
                        Group by ct.category_id
                        order by Total_Revenue DESC 
                        Limit 1""", db_connection)
category

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\2494524566.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  category = pd.read_sql(""" SELECT sum(o.list_price * o.quantity * (1-o.discount)) As Total_Revenue , ct.category_id,

   Total_Revenue  category_id   category_name
0   2.715080e+06            6  Mountain Bikes

---
## Level 4: Expert â€“ Advanced Analytical Queries
(using Pandas read_sql)

### Task 1: Find the Store with the Highest Total Revenue
Retrieve the store name and total revenue (sum of list_price * quantity) across all orders.

In [81]:
# kindly note that I used the discount column to calculate the actual revenue
Highest_store = pd.read_sql(""" SELECT st.store_id, sum(o.list_price * o.quantity * (1-o.discount)) As Total_Revenue
                        from products p
                        Join order_items o ON p.product_id = o.product_id
                        Join stocks s ON p.product_id = s.product_id
                        Left Join stores st ON s.store_id = st.store_id
                        Group by st.store_id
                        order by Total_Revenue DESC
                        Limit 1""", db_connection)
Highest_store

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\3494697870.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  Highest_store = pd.read_sql(""" SELECT st.store_id, sum(o.list_price * o.quantity * (1-o.discount)) As Total_Revenue

   store_id  Total_Revenue
0         1   7.686965e+06

### Task 2: Find all products that have never been ordered.

In [86]:
Null_products = pd.read_sql(""" SELECT p.product_id, p.product_name
                        from products p
                        Left Join order_items o ON p.product_id = o.product_id
                        Where o.order_id IS NULL""", db_connection)
Null_products

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\2439569298.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  Null_products = pd.read_sql(""" SELECT p.product_id, p.product_name

    product_id                                    product_name
0            1                                 Trek 820 - 2016
1          121                   Surly Krampus Frameset - 2018
2          125                    Trek Kids' Dual Sport - 2018
3          154           Trek Domane SLR 6 Disc Women's - 2018
4          195            Electra Townie Go! 8i Ladies' - 2018
5          267                Trek Precaliber 12 Girl's - 2018
6          284    Electra Savannah 1 (20-inch) - Girl's - 2018
7          291  Electra Sweet Ride 1 (20-inch) - Girl's - 2018
8          316            Trek Checkpoint ALR 4 Women's - 2019
9          317                    Trek Checkpoint ALR 5 - 2019
10         318            Trek Checkpoint ALR 5 Women's - 2019
11         319             Trek Checkpoint SL 5 Women's - 2019
12         320                     Trek Checkpoint SL 6 - 2019
13         321             Trek Checkpoint ALR Frameset - 2019

### Task 3: Identify the Customers Who Placed the Fewest Orders
Retrieve customer names and their total order counts, ordered in ascending order of order count.

In [96]:
lowest_customers = pd.read_sql("""SELECT c.customer_id, CONCAT(c.first_name, " ", c.last_name) As Full_name, Count(o.order_id) As No_of_orders
                                from customers c
                                Join orders o On c.customer_id = o.customer_id 
                                Group by c.customer_id
                                Order by No_of_orders, c.customer_id ASC
                                Limit 5""", db_connection)
lowest_customers

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\1125903489.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  lowest_customers = pd.read_sql("""SELECT c.customer_id, CONCAT(c.first_name, " ", c.last_name) As Full_name, Count(o.order_id) As No_of_orders

   customer_id          Full_name  No_of_orders
0           95     Letitia Franco             1
1           96   Floretta Higgins             1
2           98  Violet Valenzuela             1
3           99         Carie Kidd             1
4          100      Kellie Franco             1

### Task 4: Analyze Monthly Revenue for the Last Year (Specific to 2017)

In [103]:
# kindly note that I used the discount column to calculate the actual revenue
monthly_rev = pd.read_sql("""SELECT MONTH(o.order_date) AS Month, sum(oi.list_price * oi.quantity * (1-oi.discount)) AS Total_revenue
                                from orders o
                                Join order_items oi ON o.order_id = oi.order_id 
                                Where o.order_date Between '2017-01-01' AND '2017-12-31'
                                Group by month""", db_connection)
monthly_rev

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\4292377286.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  monthly_rev = pd.read_sql("""SELECT MONTH(o.order_date) AS Month, sum(oi.list_price * oi.quantity * (1-oi.discount)) AS Total_revenue

    Month  Total_revenue
0       1    285616.4840
1       2    312923.7470
2       3    308911.9018
3       4    227290.9131
4       5    268233.2379
5       6    378865.6535
6       7    229995.3979
7       8    290553.4554
8       9    293405.2561
9      10    310328.3090
10     11    281577.9019
11     12    259505.9849

### Task 5: Find Products That Are Low in Stock Across All Stores
Identify products where the total stock quantity (across all stores) is less than 100.

In [114]:
low_stock = pd.read_sql("""SELECT p.product_id, p.product_name, sum(s.quantity) AS total_stock
                        from products p
                        Join stocks s ON p.product_id = s.product_id
                        Group by p.product_id
                        Having total_stock < 100""", db_connection)
low_stock

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\945800812.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  low_stock = pd.read_sql("""SELECT p.product_id, p.product_name, sum(s.quantity) AS total_stock

     product_id                              product_name  total_stock
0             1                           Trek 820 - 2016         55.0
1             2        Ritchey Timberwolf Frameset - 2016         45.0
2             3           Surly Wednesday Frameset - 2016         34.0
3             4                  Trek Fuel EX 8 29 - 2016         36.0
4             5              Heller Shagamaw Frame - 2016         26.0
..          ...                                       ...          ...
308         309         Electra Townie Commute 27D - 2018         46.0
309         310  Electra Townie Commute 27D Ladies - 2018         31.0
310         311          Electra Townie Commute 8D - 2018         70.0
311         312  Electra Townie Commute 8D Ladies' - 2018         43.0
312         313  Electra Townie Original 1 Ladies' - 2018         38.0

[313 rows x 3 columns]


---

## Level 5: Additional Advanced SQL
(using Pandas read_sql)

### Task 1: Aggregate Sales by City and State
Write a query to calculate the total sales, average order value, and maximum order value for customers in each city and state.

In [139]:
sales_report = pd.read_sql("""SELECT City, State, count(DISTINCT customer_id) AS Customer_count, 
                                sum(order_value) AS Total_revenue,
                                avg(order_value) As Average_value,
                                max(order_value) As Maximum_value
                                from(
                                    SELECT c.city AS City,c.state AS State, c.customer_id,
                                    sum(oi.list_price * oi.quantity * (1-oi.discount)) AS order_value
                                    from customers c
                                    Left Join orders o ON c.customer_id= o.customer_id
                                    Join order_items oi ON o.order_id = oi.order_id
                                    Group by o.order_id, City, State
                                    ) As orders
                                Group by City , State
                                ORDER BY Total_revenue DESC""", db_connection)
sales_report

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\698944902.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sales_report = pd.read_sql("""SELECT City, State, count(DISTINCT customer_id) AS Customer_count,

,City,State,Customer_count,Total_revenue,Average_value,Maximum_value
0,Mount Vernon,NY,20,105563.3335,5278.166675,20509.4254
1,Ballston Spa,NY,17,98619.7500,5801.161765,19329.9492
2,San Angelo,TX,12,98429.2647,6151.829044,15981.1436
3,Baldwinsville,NY,7,96375.6700,10708.407778,25365.4344
4,Howard Beach,NY,12,95328.9863,7944.082192,24890.6244
...,...,...,...,...,...,...
190,Copperas Cove,TX,3,3089.5847,1029.861567,1856.6117
191,Far Rockaway,NY,2,2957.9449,1478.972450,1567.4715
192,Springfield Gardens,NY,2,1761.1534,880.576700,1258.9720
193,Tonawanda,NY,1,1256.0910,1256.091000,1256.0910
194,Westbury,NY,1,1240.1840,1240.184000,1240.1840

### Task 2: Find Top-Selling Products in 2018
Write a query to identify the products with the highest sales volume in the year 2018.

In [117]:
ProductsOf2018 = pd.read_sql("""SELECT p.product_id, p.product_name , sum(oi.quantity) As Sold_Items
                                from products p
                                Join order_items oi ON p.product_id = oi.product_id 
                                Join orders o On oi.order_id = o.order_id
                                Where o.order_date Between '2018-01-01' AND '2018-12-31'
                                Group by p.product_id
                                Order by Sold_Items DESC""", db_connection)
ProductsOf2018

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\1719411129.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ProductsOf2018 = pd.read_sql("""SELECT p.product_id, p.product_name , sum(oi.quantity) As Sold_Items

     product_id                                     product_name  Sold_Items
0            86                      Trek Girl's Kickster - 2017        12.0
1           252        Electra Townie Commute Go! Ladies' - 2018        11.0
2           235                    Electra Koa 3i Ladies' - 2018        11.0
3            92                          Haro Shredder 20 - 2017        11.0
4           263           Strider Classic 12 Balance Bike - 2018        11.0
..          ...                                              ...         ...
296         294  Electra Tiger Shark 3i (20-inch) - Boys' - 2018         1.0
297         200                           Trek Powerfly 5 - 2018         1.0
298         157           Trek Domane SL Frameset Women's - 2018         1.0
299          76               Electra Girl's Hawaii 1 16" - 2017         1.0
300          68                       Sun Bicycles Cruz 3 - 2017         1.0

[301 rows x 3 columns]

### Task 3: Calculate Month-over-Month Sales Growth
Write a query to calculate the month-over-month sales growth for the past years.

In [122]:
sales_growth = pd.read_sql("""SELECT Year(o.order_date) As Year, Month(o.order_date) As Month, 
                                sum(oi.quantity) As Sold_Items, sum(oi.list_price * oi.quantity * (1-oi.discount)) AS Total_revenue 
                                from order_items oi
                                Join orders o ON oi.order_id = o.order_id 
                                Group by Year, Month
                                ORDER BY Year, Month""", db_connection)
sales_growth

C:\Users\Client\AppData\Local\Temp\ipykernel_8160\1075967707.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sales_growth = pd.read_sql("""SELECT Year(o.order_date) As Year, Month(o.order_date) As Month,

    Year  Month  Sold_Items  Total_revenue
0   2016      1       221.0    215146.4241
1   2016      2       223.0    156112.3228
2   2016      3       213.0    180600.3285
3   2016      4       176.0    167144.0512
4   2016      5       224.0    205270.0091
5   2016      6       199.0    210562.1245
6   2016      7       211.0    199556.8089
7   2016      8       251.0    225657.3767
8   2016      9       281.0    273091.6097
9   2016     10       254.0    212078.0805
10  2016     11       181.0    182329.4124
11  2016     12       229.0    199829.9792
12  2017      1       229.0    285616.4840
13  2017      2       263.0    312923.7470
14  2017      3       296.0    308911.9018
15  2017      4       248.0    227290.9131
16  2017      5       241.0    268233.2379
17  2017      6       296.0    378865.6535
18  2017      7       249.0    229995.3979
19  2017      8       287.0    290553.4554
20  2017      9       237.0    293405.2561
21  2017     10       296.0    310328.3090
22  2017     11       241.0    281577.9019
23  2017     12       216.0    259505.9849
24  2018      1       241.0    381430.0993
25  2018      2       160.0    200658.0615
26  2018      3       290.0    363990.9935
27  2018      4       580.0    817921.8604
28  2018      6         1.0       188.9910
29  2018      7        11.0     11337.9002
30  2018      8         9.0      8377.8147
31  2018      9         4.0      8963.9647
32  2018     10         8.0      3781.1284
33  2018     11         8.0     11362.0071
34  2018     12         4.0      6516.9667